# 01. Fundamentos de Python

In [ ]:
5

5

In [ ]:
print(5)

5

In [ ]:
print("Hello World !")

Hello World !

In [ ]:
print('Hello World !')

Hello World !

In [ ]:
print("Olá Mundo ! " + "5")

Olá Mundo ! 5

In [ ]:
5 + 2

7

In [ ]:
print(5 + 2)

7

In [ ]:
produto1 = 5.00

In [ ]:
produto1

5.0

In [92]:
print(produto1)

5.0

In [ ]:
produto2 = 2000.00

In [ ]:
print(produto2)

2000.0

In [ ]:
produto3 = 1.00

In [ ]:
print(f"Soma dos Produtos: {produto1 + produto2 + produto3}")

Soma dos Produtos: 2006.0

In [ ]:
nome_do_produto1 = "Macarrão"

In [ ]:
nome_do_produto2 = "Celular"

In [ ]:
nome_do_produto3 = "Bala"

In [ ]:
print(nome_do_produto1 + " " + nome_do_produto2 + " " + nome_do_produto3)

Macarrão Celular Bala

In [ ]:
amigos = 5
aluguel = 1000.00
supermercado = 500.00
carro = 400.00

In [ ]:
total = aluguel + supermercado + carro

In [ ]:
print(total)

1900.0

In [ ]:
aluguel = 900.0

In [ ]:
print(total)

1900.0

In [ ]:
total = aluguel + supermercado + carro

In [ ]:
print(total)

1800.0

In [ ]:
print(aluguel)

900.0

In [ ]:
aluguel -= 100.0

In [ ]:
print(aluguel)

800.0

In [ ]:
aluguel -= 100.0

In [ ]:
print(aluguel)

700.0

In [ ]:
amigos = 6
aluguel = 1000.00
supermercado = 500.00
carro = 400.00

In [ ]:
print(amigos)

6

In [ ]:
total_de_carro = carro * 2

In [ ]:
total = aluguel + supermercado + total_de_carro

In [ ]:
print(total)

2300.0

In [ ]:
total_por_pessoa = total / amigos

In [ ]:
print(total_por_pessoa)

383.3333333333333

In [ ]:
type(aluguel)

float

In [ ]:
type(total_por_pessoa)

float

In [ ]:
type(nome_do_produto1)

str

In [ ]:
pedro_tem_carteira_motorista = True

mario_tem_carteira_motorista = False

In [ ]:
type(pedro_tem_carteira_motorista)

bool

In [ ]:
type(mario_tem_carteira_motorista)

bool

In [ ]:
texto = "    Fabrício CARRaro  da alura   "
print(texto)

    Fabrício CARRaro  da alura

In [ ]:
print(texto.lower())

    fabrício carraro  da alura

In [ ]:
print(texto.upper())

    FABRÍCIO CARRARO  DA ALURA

In [ ]:
print(texto.strip())

Fabrício CARRaro  da alura

In [ ]:
print(texto.replace("  "," "))

  Fabrício CARRaro da alura

In [ ]:
texto = texto.strip().upper().replace("  ", " ")

In [ ]:
print(texto)

FABRÍCIO CARRARO DA ALURA

In [ ]:
nome = input("Digite seu nome: ")

Digite seu nome: John Doe

In [ ]:
print(nome)

John Doe

In [ ]:
idade = input("Digite sua idade: ")

Digite sua idade: 115

In [ ]:
print(idade)

115

In [ ]:
type(nome)

str

In [ ]:
type(idade)

str

In [ ]:
idade = int(idade)

In [ ]:
type(idade)

int

In [ ]:
print(f"A pessoa se chama {nome} e tem {idade} anos de idade")

A pessoa se chama John Doe e tem 115 anos de idade

In [ ]:
idade = int(input("Digite sua idade: "))

Digite sua idade: 116

In [ ]:
type(idade)

int

In [ ]:
if idade >= 18:
    print(f"O {nome} pode entrar na festa porque ele é maior de idade")
    print(f"Ele tem {idade} anos de idade")
else:
    print(f"O {nome} NÃO PODE entrar na festa porque ele é MENOR de idade")
    print(f"Ele tem {idade} anos de idade")

O John Doe pode entrar na festa porque ele é maior de idade
Ele tem 116 anos de idade

In [ ]:
media = float(input("Digite sua media: "))

Digite sua media: 9.7

In [ ]:
media = float(input("Digite sua media: "))

if media >= 7.0:
  print("Aprovado")
elif media >= 5.0 and media < 7.0:
  print("Recuperação")
else:
  print("Reprovado")

Digite sua media: 9.9
Aprovado

### **Rodando a IA no Google Colab (Gemini)**

In [ ]:
import os

from google.colab import userdata

# userdata.get('Gemini_API_Key')

os.environ["GOOGLE_API_KEY"] = userdata.get('Gemini_API_Key')

In [94]:
from google import genai

client = genai.Client()

In [95]:
resposta = client.models.generate_content(model='gemini-2.5-flash', contents="What is Agentic AI ?")

In [96]:
print(resposta.text)

**Agentic AI** refers to an artificial intelligence system that possesses the ability to **take initiative, act autonomously, and pursue goals in a dynamic environment without requiring constant human intervention.**

Instead of simply waiting for a prompt and generating a response (like a traditional chatbot or a basic LLM), an agentic AI is designed to understand a high-level objective, break it down into smaller steps, execute those steps, make decisions along the way, adapt to new information, and even self-correct if it encounters issues, all in pursuit of its ultimate goal.

Think of it this way:

*   **Traditional AI:** You ask it to "Summarize this document." It does. End of interaction.
*   **Agentic AI:** You ask it to "Plan and book a trip to Paris for next month, including flights, accommodation, and a few cultural activities." It doesn't just give you a list of ideas. It would:
    *   Search for flights within your budget.
    *   Look for hotels matching your preferences.
    *   Check availability for museums or shows.
    *   Handle potential conflicts (e.g., a flight time clashing with a show booking).
    *   Present you with a full itinerary, possibly even making the bookings itself if given permission, and inform you of any issues it couldn't resolve.

**Key Characteristics of Agentic AI:**

1.  **Goal-Oriented:** It operates with a specific objective or task in mind.
2.  **Autonomy/Proactivity:** It doesn't wait for step-by-step instructions. It figures out what needs to be done.
3.  **Perception & Interaction:** It can "perceive" its environment (digital or physical) and "act" upon it using various tools or APIs.
4.  **Planning & Reasoning:** It can generate plans, sequences of actions, and reason about the best way to achieve its goal.
5.  **Memory & Context:** It can maintain a working memory of its current task, past actions, and relevant information to inform future decisions.
6.  **Tool Use:** It can leverage external tools, software, databases, and APIs (like web browsers, calendar apps, code interpreters, other AI models) to extend its capabilities.
7.  **Self-Correction & Adaptation:** If an action fails or the environment changes, it can recognize the issue, re-evaluate its plan, and try a different approach.
8.  **Iterative Process:** It often works in a loop of planning, acting, observing, and reflecting.

**How Agentic AI Works (Simplified Loop):**

1.  **Goal/Prompt:** Receives a high-level objective from a human.
2.  **Planning:** Uses its intelligence (often powered by a large language model) to break the goal into smaller, manageable sub-tasks and create a plan.
3.  **Action:** Executes a step from its plan, using appropriate tools (e.g., performing a web search, writing code, sending an email).
4.  **Observation:** Monitors the outcome of its action, assessing whether it was successful or if new information has emerged.
5.  **Reflection/Reasoning:** Evaluates the observation against its goal and plan. Did it get closer to the goal? Are there new obstacles? Does the plan need adjustment?
6.  **Loop:** Repeats the planning-action-observation-reflection cycle until the goal is achieved or it determines it cannot proceed further.

**Why is it significant?**

Agentic AI represents a significant step towards more capable and genuinely helpful AI systems. It moves AI from being a reactive tool to a proactive assistant, capable of tackling more complex, multi-step problems that require sustained effort and adaptive decision-making. It's a key component in the development of more advanced general-purpose AI.

**Loops**

In [97]:
n = 1

while n <= 5:
  print("*")
  n += 1

*
*
*
*
*

In [98]:
chat = client.chats.create(model='gemini-2.5-flash')

In [99]:
resposta2 = chat.send_message("O que é a Inteligência Artificial ?")

In [100]:
#print(resposta2)
print(resposta2.text)

A **Inteligência Artificial (IA)** é um campo da ciência da computação que se dedica a criar máquinas e sistemas capazes de simular, emular e, em alguns casos, superar capacidades cognitivas humanas. Em termos mais simples, a IA busca desenvolver inteligência em máquinas, permitindo que elas realizem tarefas que normalmente exigiriam inteligência humana.

**O que a IA busca fazer?**

A IA se propõe a dotar as máquinas com a capacidade de:

1.  **Aprender (Machine Learning):** Adquirir conhecimento a partir de dados, identificar padrões e melhorar seu desempenho ao longo do tempo, sem serem explicitamente programadas para cada cenário.
2.  **Raciocinar:** Aplicar lógica, regras e algoritmos para resolver problemas, fazer inferências e tomar decisões.
3.  **Perceber:** Interpretar informações sensoriais, como imagens (visão computacional), sons (reconhecimento de fala) e texto.
4.  **Compreender a Linguagem Natural (Processamento de Linguagem Natural - PLN):** Entender, interpretar e gerar linguagem humana (escrita e falada).
5.  **Resolver Problemas:** Encontrar soluções para desafios complexos, seja em jogos, planejamento ou outras áreas.
6.  **Interagir:** Conversar, responder perguntas e colaborar com humanos de forma inteligente.

**Como a IA funciona?**

A IA não é magia, mas sim o resultado de algoritmos complexos, modelos matemáticos e uma vasta quantidade de dados. As máquinas são "treinadas" com esses dados para identificar padrões, fazer previsões e tomar decisões.

**Principais Pilares e Subcampos da IA:**

*   **Machine Learning (Aprendizado de Máquina):** É o subcampo mais proeminente da IA hoje. Foca em sistemas que aprendem com dados, em vez de serem explicitamente programados.
    *   **Deep Learning (Aprendizado Profundo):** Um subcampo do Machine Learning que utiliza redes neurais artificiais com muitas camadas ("profundas") para processar grandes volumes de dados e reconhecer padrões complexos, como em imagens e fala.
*   **Processamento de Linguagem Natural (PLN/NLP):** Permite que computadores entendam, interpretem e gerem linguagem humana. Exemplos: tradução automática, chatbots, análise de sentimento.
*   **Visão Computacional (Computer Vision):** Habilita computadores a "ver" e interpretar imagens e vídeos, extraindo informações significativas. Exemplos: reconhecimento facial, carros autônomos, diagnóstico médico por imagem.
*   **Robótica:** Embora a robótica seja o estudo e a criação de robôs (máquinas físicas), a IA é frequentemente usada para dar "cérebros" a esses robôs, permitindo-lhes interagir com o ambiente de forma autônoma e inteligente.
*   **Sistemas Especialistas:** Programas que simulam o conhecimento e o processo de raciocínio de um especialista humano em um domínio específico.

**Tipos de IA:**

Geralmente, a IA é categorizada em três níveis:

1.  **IA Estreita (Narrow AI / Weak AI):** É a IA que temos hoje. É projetada e treinada para uma tarefa específica. Exemplos: assistentes de voz (Siri, Alexa), sistemas de recomendação (Netflix), carros autônomos, filtros de spam. Ela é muito boa em *uma* coisa, mas não possui inteligência geral.
2.  **IA Geral (General AI / Strong AI):** É uma IA hipotética que possui inteligência em nível humano, capaz de entender, aprender e aplicar sua inteligência a qualquer tarefa intelectual que um ser humano pode fazer. Ainda não existe.
3.  **Superinteligência Artificial (Superintelligence):** Uma IA hipotética que excede em muito a inteligência humana em todos os aspectos, incluindo criatividade, resolução de problemas e habilidades sociais.

**Aplicações da IA no dia a dia:**

*   **Assistentes Virtuais:** Siri, Google Assistant, Alexa.
*   **Recomendações:** Netflix, Amazon, Spotify.
*   **Carros Autônomos:** Tesla, Waymo.
*   **Diagnóstico Médico:** Análise de exames de imagem, identificação de doenças.
*   **Segurança:** Reconhecimento facial, detecção de fraudes.
*   **Finanças:** Algoritmos de negociação, análise de risco.
*   **Educação:** Plataformas de aprendizado adaptativo.
*   **Atendimento ao Cliente:** Chatbots.

Em resumo, a Inteligência Artificial é uma área revolucionária que busca expandir as capacidades das máquinas para além da programação tradicional, permitindo-lhes aprender, raciocinar e interagir de formas cada vez mais sofisticadas, impactando profundamente quase todos os aspectos da nossa vida moderna.

In [102]:
resposta3 = chat.send_message("Quando foi lançado o ChatGPT ?")

print(resposta3.text)

O **ChatGPT** foi lançado em **30 de novembro de 2022**.

Foi neste dia que a OpenAI o disponibilizou ao público para testes e uso inicial, causando um grande impacto e gerando uma enorme discussão sobre as capacidades da Inteligência Artificial.

In [ ]:
chat.get_history()

[UserContent(
   parts=[
     Part(
       text='O que é a Inteligência Artificial ?'
     ),
   ],
   role='user'
 ),
 Content(
   parts=[
     Part(
       text="""A Inteligência Artificial (IA) é um campo da ciência da computação dedicado à criação de máquinas e sistemas que podem **simular e executar tarefas que normalmente exigiriam inteligência humana**. O objetivo principal da IA é desenvolver sistemas que possam aprender, raciocinar, compreender, perceber, tomar decisões e resolver problemas de forma autônoma.

 ### O que a IA busca imitar na inteligência humana?

 *   **Aprendizagem:** A capacidade de adquirir e aplicar conhecimento a partir de dados e experiência (ex: aprender a identificar padrões em imagens ou textos).
 *   **Raciocínio:** A capacidade de usar lógica e regras para resolver problemas e tomar decisões (ex: um sistema de IA que planeja a rota mais eficiente).
 *   **Percepção:** A capacidade de interpretar informações sensoriais, como imagens, sons e fala (ex: reconhecimento facial ou de voz).
 *   **Compreensão da Linguagem Natural:** A capacidade de entender e gerar linguagem humana, seja escrita ou falada (ex: assistentes de voz como a Siri ou a Alexa).
 *   **Resolução de Problemas:** A capacidade de encontrar soluções para desafios complexos.
 *   **Adaptação:** A capacidade de ajustar-se a novas situações e informações.

 ### Como a IA funciona (de forma simplificada)?

 A IA opera processando grandes volumes de dados (big data) com algoritmos complexos. Esses algoritmos permitem que os sistemas identifiquem padrões, façam previsões e tomem decisões. O processo geralmente envolve:

 1.  **Coleta de Dados:** Alimentar o sistema com informações relevantes.
 2.  **Treinamento:** Usar algoritmos para "ensinar" o sistema a reconhecer padrões e relacionamentos nos dados.
 3.  **Avaliação e Ajuste:** Testar o sistema e refinar seus algoritmos para melhorar o desempenho.
 4.  **Inferência/Execução:** O sistema aplica o conhecimento adquirido para realizar novas tarefas ou fazer previsões.

 ### Tipos de Inteligência Artificial:

 1.  **IA Fraca (ou IA Estreita/Narrow AI):** É o tipo de IA que existe atualmente e é mais comum. Ela é projetada e treinada para uma **tarefa específica**.
     *   **Exemplos:** Sistemas de reconhecimento facial, assistentes de voz (Siri, Alexa), sistemas de recomendação (Netflix, Amazon), filtros de spam, carros autônomos.

 2.  **IA Geral (ou IA Forte/General AI - AGI):** É uma IA hipotética que possuiria inteligência em nível humano, com a capacidade de entender, aprender e aplicar sua inteligência a qualquer problema ou tarefa que um ser humano possa fazer. Ainda não existe.

 3.  **Superinteligência Artificial:** Uma IA hipotética que superaria a inteligência humana em todos os aspectos, incluindo criatividade, resolução de problemas e habilidades sociais. Ainda mais teórica.

 ### Principais Subcampos da IA:

 *   **Machine Learning (Aprendizado de Máquina):** Um subcampo da IA que permite que os sistemas aprendam com dados sem serem explicitamente programados. É o motor por trás da maioria das aplicações de IA atuais.
     *   **Deep Learning (Aprendizado Profundo):** Um subcampo do Machine Learning que utiliza redes neurais artificiais com muitas camadas (daí o "profundo") para aprender padrões complexos a partir de grandes quantidades de dados.
 *   **Processamento de Linguagem Natural (PLN/NLP):** Permite que os computadores entendam, interpretem e gerem linguagem humana.
 *   **Visão Computacional (Computer Vision):** Permite que os computadores "vejam" e interpretem imagens e vídeos do mundo real.
 *   **Robótica:** Envolve a concepção, construção, operação e uso de robôs, muitas vezes integrando IA para dar aos robôs autonomia e capacidade de decisão.

 ### Aplicações da IA:

 A IA está presente em diversas áreas do nosso dia a dia, como:

 *   **Saúde:** Diagnóstico de doenças, descoberta de medicamentos, cirurgias assistidas.
 *   **Finanças:** Detecção de fraudes, negociação de ações, gerenciamento de riscos.
 *   **Transporte:** Carros autônomos, otimização de rotas.
 *   **Entretenimento:** Recomendações personalizadas, criação de conteúdo.
 *   **Atendimento ao Cliente:** Chatbots e assistentes virtuais.
 *   **Indústria:** Manutenção preditiva, controle de qualidade.

 Em resumo, a Inteligência Artificial é a capacidade das máquinas de pensar, aprender e agir como humanos, e é uma das tecnologias mais transformadoras do nosso tempo, com um potencial imenso para impactar todos os aspectos da sociedade."""
     ),
   ],
   role='model'
 ),
 UserContent(
   parts=[
     Part(
       text='Quando foi lançado o ChatGPT ?'
     ),
   ],
   role='user'
 ),
 Content(
   parts=[
     Part(
       text="""O ChatGPT foi lançado pela OpenAI em **30 de novembro de 2022**.

 Foi disponibilizado como uma "prévia de pesquisa" (research preview) gratuita para o público, com o objetivo de coletar feedback e aprender sobre seu uso. Ele rapidamente ganhou uma popularidade massiva devido à sua capacidade impressionante de gerar texto e interagir de forma conversacional."""
     ),
   ],
   role='model'
 )]

In [104]:
prompt = input("Digite sua pergunta: ")

while prompt != "fim":
  resposta4 = chat.send_message(prompt)
  print(f"{resposta4.text} \n")
  prompt = input("Digite sua pergunta: ")

  print(resposta4.text)

Digite sua pergunta: O que é Deep Learning ?
**Deep Learning** (Aprendizado Profundo, em português) é um subcampo do **Machine Learning** (Aprendizado de Máquina), que por sua vez é um subcampo da **Inteligência Artificial (IA)**.

A principal característica que define o Deep Learning é o uso de **redes neurais artificiais com múltiplas camadas (profundas)** para aprender e extrair padrões complexos a partir de grandes volumes de dados.

Vamos destrinchar isso:

1.  **Redes Neurais Artificiais:**
    *   Inspiradas na estrutura e funcionamento do cérebro humano, as redes neurais artificiais são compostas por "neurônios" (nós de processamento) organizados em camadas.
    *   Cada neurônio recebe entradas, aplica um processamento a elas (geralmente uma soma ponderada seguida de uma função de ativação) e produz uma saída.
    *   As conexões entre os neurônios têm "pesos" que são ajustados durante o processo de treinamento.

2.  **A Origem do "Deep" (Profundo):**
    *   Uma rede neural tradicional pode ter uma camada de entrada, uma ou poucas camadas ocultas e uma camada de saída.
    *   No Deep Learning, a rede possui **muitas camadas ocultas** (daí o "profundo"). Essa profundidade permite que a rede aprenda representações hierárquicas dos dados.
    *   Imagine o reconhecimento de imagens:
        *   A primeira camada oculta pode aprender a detectar bordas e linhas simples.
        *   A segunda camada pode combinar essas bordas para formar formas mais complexas (círculos, retângulos).
        *   As camadas seguintes podem identificar partes de objetos (olhos, nariz, boca para um rosto) e, finalmente, as últimas camadas podem reconhecer o objeto completo (uma face humana).

3.  **Como o Deep Learning se diferencia do Machine Learning tradicional:**
    *   **Extração de Características (Feature Engineering):** Em Machine Learning tradicional, muitas vezes é necessário que engenheiros humanos extraiam manualmente as "características" (features) relevantes dos dados para que o algoritmo possa aprender. Por exemplo, para reconhecer um gato, você poderia programar para identificar bigodes, orelhas pontudas, etc.
    *   **No Deep Learning, a rede aprende a extrair as características automaticamente.** As múltiplas camadas aprendem a identificar, por si mesmas, quais são os padrões mais relevantes nos dados brutos. Isso elimina uma etapa manual complexa e crucial, permitindo que os modelos lidem com dados muito mais complexos e brabalhem de forma mais autônoma.

**Principais Vantagens do Deep Learning:**

*   **Alto Desempenho com Grande Volume de Dados:** Quanto mais dados ele recebe, melhor tende a performar.
*   **Aprendizado Automático de Características:** Não exige intervenção humana para extrair features.
*   **Versatilidade:** Pode ser aplicado a diversos tipos de dados (imagens, áudio, texto, vídeo, dados numéricos).
*   **Reconhecimento de Padrões Complexos:** Capaz de identificar relações não lineares e padrões sutis que seriam difíceis de programar manualmente.

**Tipos Comuns de Redes Neurais Profundas:**

*   **CNNs (Convolutional Neural Networks):** Especialmente eficazes para processar dados com estrutura semelhante a grades, como imagens e vídeos. Usadas em reconhecimento facial, carros autônomos.
*   **RNNs (Recurrent Neural Networks):** Projetadas para lidar com dados sequenciais, como texto e séries temporais. Muito usadas em processamento de linguagem natural (PLN) e reconhecimento de fala (LSTMs e GRUs são variações populares).
*   **Transformers:** Uma arquitetura mais recente que revolucionou o PLN, sendo a base de modelos como o GPT (incluindo o ChatGPT) e o BERT, permitindo uma compreensão de contexto muito mais avançada.
*   **GANs (Generative Adversarial Networks):** Usadas para gerar novos dados que se parecem com os dados de treinamento (por exemplo, criar imagens realistas de pessoas que não existem).

**Aplicações do Deep Learning:**

*   **Visão Computacional:** Reconhecimento de objetos, detecção facial, carros autônomos, diagnóstico médico por imagem.
*   **Processamento de Linguagem Natural (PLN):** Tradução automática (Google Translate), chatbots (ChatGPT), análise de sentimento, sumariação de texto.
*   **Reconhecimento de Fala:** Assistentes virtuais (Siri, Alexa), transcrição de áudio.
*   **Sistemas de Recomendação:** Sugestões de produtos (Amazon), filmes (Netflix), músicas (Spotify).
*   **Medicina:** Descoberta de medicamentos, análise de prontuários, previsão de doenças.

Em resumo, o Deep Learning é uma das forças motrizes por trás da atual revolução da IA, permitindo que as máquinas alcancem níveis de desempenho impressionantes em tarefas que antes eram exclusivas da inteligência humana.

Digite sua pergunta: fim
**Deep Learning** (Aprendizado Profundo, em português) é um subcampo do **Machine Learning** (Aprendizado de Máquina), que por sua vez é um subcampo da **Inteligência Artificial (IA)**.

A principal característica que define o Deep Learning é o uso de **redes neurais artificiais com múltiplas camadas (profundas)** para aprender e extrair padrões complexos a partir de grandes volumes de dados.

Vamos destrinchar isso:

1.  **Redes Neurais Artificiais:**
    *   Inspiradas na estrutura e funcionamento do cérebro humano, as redes neurais artificiais são compostas por "neurônios" (nós de processamento) organizados em camadas.
    *   Cada neurônio recebe entradas, aplica um processamento a elas (geralmente uma soma ponderada seguida de uma função de ativação) e produz uma saída.
    *   As conexões entre os neurônios têm "pesos" que são ajustados durante o processo de treinamento.

2.  **A Origem do "Deep" (Profundo):**
    *   Uma rede neural tradicional pode ter uma camada de entrada, uma ou poucas camadas ocultas e uma camada de saída.
    *   No Deep Learning, a rede possui **muitas camadas ocultas** (daí o "profundo"). Essa profundidade permite que a rede aprenda representações hierárquicas dos dados.
    *   Imagine o reconhecimento de imagens:
        *   A primeira camada oculta pode aprender a detectar bordas e linhas simples.
        *   A segunda camada pode combinar essas bordas para formar formas mais complexas (círculos, retângulos).
        *   As camadas seguintes podem identificar partes de objetos (olhos, nariz, boca para um rosto) e, finalmente, as últimas camadas podem reconhecer o objeto completo (uma face humana).

3.  **Como o Deep Learning se diferencia do Machine Learning tradicional:**
    *   **Extração de Características (Feature Engineering):** Em Machine Learning tradicional, muitas vezes é necessário que engenheiros humanos extraiam manualmente as "características" (features) relevantes dos dados para que o algoritmo possa aprender. Por exemplo, para reconhecer um gato, você poderia programar para identificar bigodes, orelhas pontudas, etc.
    *   **No Deep Learning, a rede aprende a extrair as características automaticamente.** As múltiplas camadas aprendem a identificar, por si mesmas, quais são os padrões mais relevantes nos dados brutos. Isso elimina uma etapa manual complexa e crucial, permitindo que os modelos lidem com dados muito mais complexos e brabalhem de forma mais autônoma.

**Principais Vantagens do Deep Learning:**

*   **Alto Desempenho com Grande Volume de Dados:** Quanto mais dados ele recebe, melhor tende a performar.
*   **Aprendizado Automático de Características:** Não exige intervenção humana para extrair features.
*   **Versatilidade:** Pode ser aplicado a diversos tipos de dados (imagens, áudio, texto, vídeo, dados numéricos).
*   **Reconhecimento de Padrões Complexos:** Capaz de identificar relações não lineares e padrões sutis que seriam difíceis de programar manualmente.

**Tipos Comuns de Redes Neurais Profundas:**

*   **CNNs (Convolutional Neural Networks):** Especialmente eficazes para processar dados com estrutura semelhante a grades, como imagens e vídeos. Usadas em reconhecimento facial, carros autônomos.
*   **RNNs (Recurrent Neural Networks):** Projetadas para lidar com dados sequenciais, como texto e séries temporais. Muito usadas em processamento de linguagem natural (PLN) e reconhecimento de fala (LSTMs e GRUs são variações populares).
*   **Transformers:** Uma arquitetura mais recente que revolucionou o PLN, sendo a base de modelos como o GPT (incluindo o ChatGPT) e o BERT, permitindo uma compreensão de contexto muito mais avançada.
*   **GANs (Generative Adversarial Networks):** Usadas para gerar novos dados que se parecem com os dados de treinamento (por exemplo, criar imagens realistas de pessoas que não existem).

**Aplicações do Deep Learning:**

*   **Visão Computacional:** Reconhecimento de objetos, detecção facial, carros autônomos, diagnóstico médico por imagem.
*   **Processamento de Linguagem Natural (PLN):** Tradução automática (Google Translate), chatbots (ChatGPT), análise de sentimento, sumariação de texto.
*   **Reconhecimento de Fala:** Assistentes virtuais (Siri, Alexa), transcrição de áudio.
*   **Sistemas de Recomendação:** Sugestões de produtos (Amazon), filmes (Netflix), músicas (Spotify).
*   **Medicina:** Descoberta de medicamentos, análise de prontuários, previsão de doenças.

Em resumo, o Deep Learning é uma das forças motrizes por trás da atual revolução da IA, permitindo que as máquinas alcancem níveis de desempenho impressionantes em tarefas que antes eram exclusivas da inteligência humana.

### Estruturas de Dados

In [105]:
lista_de_nomes = ["Maria Silva", "João Santos", "Ana Oliveira", "Pedro Costa", "juliana Pereira"]

In [106]:
print(lista_de_nomes[3])

Pedro Costa

In [107]:
lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]

In [108]:
print(lista_de_nomes[3])

Pedro Costa

In [109]:
for i in range(len(lista_de_medias)):   # Percorre a lista de médias e some 1 ao valor de cada média.

  lista_de_medias[i] = lista_de_medias[i] + 1.0

  if lista_de_medias[i] > 10.0:
    lista_de_medias[i] = 10.0

  print(lista_de_medias[i])

9.9
8.5
5.2
2.4
10.0

In [110]:
lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]

In [111]:
n = 0

while n < len(lista_de_medias):

  lista_de_medias[n] += 1.0

  if lista_de_medias[n] > 10.0:
    lista_de_medias[n] = 10.0

  print(lista_de_medias[n])

  n += 1

9.9
8.5
5.2
2.4
10.0

In [112]:
len(lista_de_medias)

5

In [113]:
lista_de_medias[len(lista_de_medias) - 1 ]

10.0

In [114]:
lista_de_medias[-1]

10.0

In [115]:
lista_de_nomes

['Maria Silva',
 'João Santos',
 'Ana Oliveira',
 'Pedro Costa',
 'juliana Pereira']

In [116]:
lista_de_nomes[1:]

['João Santos', 'Ana Oliveira', 'Pedro Costa', 'juliana Pereira']

In [117]:
lista_de_nomes[0:]

['Maria Silva',
 'João Santos',
 'Ana Oliveira',
 'Pedro Costa',
 'juliana Pereira']

In [118]:
lista_de_nomes[:]

['Maria Silva',
 'João Santos',
 'Ana Oliveira',
 'Pedro Costa',
 'juliana Pereira']

In [119]:
lista_de_nomes[1:4]

['João Santos', 'Ana Oliveira', 'Pedro Costa']

In [120]:
lista_de_nomes[:4]

['Maria Silva', 'João Santos', 'Ana Oliveira', 'Pedro Costa']

In [121]:
lista_de_nomes.append("Fabrício")

In [122]:
lista_de_nomes

['Maria Silva',
 'João Santos',
 'Ana Oliveira',
 'Pedro Costa',
 'juliana Pereira',
 'Fabrício']

In [123]:
lista_de_nomes.extend(["Joana da Silva", "Paulo Silveira"])

In [124]:
lista_de_nomes

['Maria Silva',
 'João Santos',
 'Ana Oliveira',
 'Pedro Costa',
 'juliana Pereira',
 'Fabrício',
 'Joana da Silva',
 'Paulo Silveira']

In [125]:
lista_de_nomes.append(["Marcio Costa","Natalia Pedreira"])

In [126]:
lista_de_nomes[8]

['Marcio Costa', 'Natalia Pedreira']

In [127]:
lista_de_nomes[8][0]

'Marcio Costa'

In [128]:
lista_de_nomes = ["Maria Silva", "João Santos", "Ana Oliveira", "Pedro Costa", "juliana Pereira"]

In [129]:
lista_de_nomes.extend(["Joana da Silva", "Paulo Silveira"])

In [130]:
lista_de_nomes

['Maria Silva',
 'João Santos',
 'Ana Oliveira',
 'Pedro Costa',
 'juliana Pereira',
 'Joana da Silva',
 'Paulo Silveira']

In [131]:
lista_de_nomes.remove("Paulo Silveira")

In [132]:
lista_de_nomes

['Maria Silva',
 'João Santos',
 'Ana Oliveira',
 'Pedro Costa',
 'juliana Pereira',
 'Joana da Silva']

In [133]:
lista_de_nomes.pop()

'Joana da Silva'

In [134]:
lista_de_nomes

['Maria Silva',
 'João Santos',
 'Ana Oliveira',
 'Pedro Costa',
 'juliana Pereira']

In [135]:
lista_de_nomes.pop(2)

'Ana Oliveira'

In [136]:
lista_de_nomes

['Maria Silva', 'João Santos', 'Pedro Costa', 'juliana Pereira']

# Dicionários
# "chave".valor

In [137]:
dict_de_nomes_e_medias = {
    "Maria Silva": 8.9,
    "João Santos": 7.5,
    "Ana Oliveira": 4.2,
    "Pedro Costa": 1.4,
    "juliana Pereira": 9.5
}

In [138]:
dict_de_nomes_e_medias

{'Maria Silva': 8.9,
 'João Santos': 7.5,
 'Ana Oliveira': 4.2,
 'Pedro Costa': 1.4,
 'juliana Pereira': 9.5}

In [139]:
dict_de_nomes_e_medias["Maria Silva"]

8.9

In [140]:
dict_de_nomes_e_medias.get("Maria Silva")

8.9

In [141]:
dict_de_nomes_e_medias

{'Maria Silva': 8.9,
 'João Santos': 7.5,
 'Ana Oliveira': 4.2,
 'Pedro Costa': 1.4,
 'juliana Pereira': 9.5}

In [142]:
dict_de_nomes_e_medias.pop("juliana Pereira")

9.5

In [143]:
dict_de_nomes_e_medias

{'Maria Silva': 8.9,
 'João Santos': 7.5,
 'Ana Oliveira': 4.2,
 'Pedro Costa': 1.4}

In [144]:
dict_de_nomes_e_medias.items()

dict_items([('Maria Silva', 8.9), ('João Santos', 7.5), ('Ana Oliveira', 4.2), ('Pedro Costa', 1.4)])

In [145]:
dict_de_nomes_e_medias.keys()

dict_keys(['Maria Silva', 'João Santos', 'Ana Oliveira', 'Pedro Costa'])

In [146]:
dict_de_nomes_e_medias.values()

dict_values([8.9, 7.5, 4.2, 1.4])

# Desafio: Usar dicionários de forma que as chaves sejam "nome" e "média" e os valores sejam os nomes e médias dos alunos

In [147]:
dict_desafio = [
    {"nome": "Maria Silva",  "media": 8.9},
    {"nome": "João Santos",  "media": 7.5},
    {"nome": "Ana Oliveira", "media": 4.2},
    {"nome": "Pedro Costa",  "media": 1.4},
]

In [148]:
dict_desafio

[{'nome': 'Maria Silva', 'media': 8.9},
 {'nome': 'João Santos', 'media': 7.5},
 {'nome': 'Ana Oliveira', 'media': 4.2},
 {'nome': 'Pedro Costa', 'media': 1.4}]

In [149]:
dict_desafio[0]

{'nome': 'Maria Silva', 'media': 8.9}

In [150]:
dict_desafio[0]["media"]

8.9

In [151]:
nomes = ['Maria', 'João', 'Ana', 'Pedro', 'Juliana']

print(nomes[-1])  # Exibe 'Juliana'
print(nomes[-2])  # Exibe 'Pedro'

Juliana
Pedro

In [152]:
# Exemplo de slicing com índice negativo

ultimos_tres = nomes[-3:]

print(ultimos_tres)  # Exibe ['Ana', 'Pedro', 'Juliana']

['Ana', 'Pedro', 'Juliana']

In [153]:
dict_desafio = [
    {"nome": "Maria Silva",  "media": 8.9},
    {"nome": "João Santos",  "media": 7.5},
    {"nome": "Ana Oliveira", "media": 4.2},
    {"nome": "Pedro Costa",  "media": 1.4},
]

In [154]:
n = 0
while n < len(dict_desafio):
    print (dict_desafio[n])
    n += 1

{'nome': 'Maria Silva', 'media': 8.9}
{'nome': 'João Santos', 'media': 7.5}
{'nome': 'Ana Oliveira', 'media': 4.2}
{'nome': 'Pedro Costa', 'media': 1.4}

In [155]:
for elemento in dict_desafio:
    print(elemento)

{'nome': 'Maria Silva', 'media': 8.9}
{'nome': 'João Santos', 'media': 7.5}
{'nome': 'Ana Oliveira', 'media': 4.2}
{'nome': 'Pedro Costa', 'media': 1.4}

In [156]:
for n in range(5):
    print(n)

0
1
2
3
4

In [157]:
for n in range(2, 7):
    print(n)

2
3
4
5
6

In [158]:
for n in range(2, 7, 2):
    print(n)

2
4
6

In [159]:
pessoa = {
    "nome": "Fabrício",
    "idade": 19,
    "altura": 1.87
}

print(pessoa)

{'nome': 'Fabrício', 'idade': 19, 'altura': 1.87}

In [160]:
for key in pessoa:
    print(key)

nome
idade
altura

In [161]:
pessoa.items()

dict_items([('nome', 'Fabrício'), ('idade', 19), ('altura', 1.87)])

In [162]:
for key,value in pessoa.items():
    print(f"A chave é {key} e o valor é {value}")

A chave é nome e o valor é Fabrício
A chave é idade e o valor é 19
A chave é altura e o valor é 1.87

In [163]:
for n in range(0,11):
    if n % 2 == 0 :
        print(n)

0
2
4
6
8
10

In [164]:
texto1 = "    Fabrício CARRaro  da alura   "
texto2 = "mArIA    aNA     sAntoS.  pereiRA"
texto3 = "  PeDRO.  alvaRes  cabrAl "
texto4 = "   anA   caroLINa.    FerreirA  "
texto5 = "  rObertO.   carlOS.     OliveiRa  "

In [165]:
texto1.split()

['Fabrício', 'CARRaro', 'da', 'alura']

In [166]:
len(texto1.split())

4

In [167]:
def escreve_texto_corretamente(texto):
    texto_novo = texto.strip().upper().replace("  "," ")
    #lista_de_palavras = texto_novo.split()
    #nome_final = " ".join(lista_de_palavras)
    #print(nome_final)
    print(texto_novo)

In [168]:
def escreve_texto_corretamente2(texto):
    texto_novo = texto.upper()
    lista_de_palavras = texto_novo.split()
    nome_final = " ".join(lista_de_palavras)
    print(nome_final)
    #print(texto_novo)

In [169]:
escreve_texto_corretamente2(texto1)

FABRÍCIO CARRARO DA ALURA

In [170]:
escreve_texto_corretamente2(texto2)

MARIA ANA SANTOS. PEREIRA

In [171]:
def escreve_texto_corretamente_alternativa(texto):
    nome_final = " ".join(texto.upper().split())
    return nome_final

In [172]:
escreve_texto_corretamente_alternativa(texto1)

'FABRÍCIO CARRARO DA ALURA'

In [173]:
salas_de_aula = ["sala 1", "sala 2", "sala 3"]

In [174]:
import random

def aloca_alunos_em_salas(nome_do_aluno, lista_de_salas):
    sala_do_aluno = random.choice(lista_de_salas)

    dict_aluno = {
        "nome": nome_do_aluno,
        "sala": sala_do_aluno
    }
    print(dict_aluno)

In [175]:
nome_processado = escreve_texto_corretamente_alternativa(texto1)

In [176]:
#aloca_alunos_em_salas(nome_processado, salas_de_aula)
aloca_alunos_em_salas(nome_processado, ["Classe 1", "Classe 2", "Classe 3"])

{'nome': 'FABRÍCIO CARRARO DA ALURA', 'sala': 'Classe 1'}

In [177]:
"""
Desafio:

1. Pedir para IA gerar em Python uma lista de 20 emails para você.
2. Criar uma função que vai receber uma lista de emails , percorrer esta lista de emails e para cada email da lista,
 ela irá chamar o gemini e pedir para ela resumir todos os emails em apenas 1 linha, definindo o que a pessoa queria no
  email.
"""

'\nDesafio:\n\n1. Pedir para IA gerar em Python uma lista de 20 emails para você.\n2. Criar uma função que vai receber uma lista de emails , percorrer esta lista de emails e para cada email da lista,\n ela irá chamar o gemini e pedir para ela resumir todos os emails em apenas 1 linha, definindo o que a pessoa queria no\n  email.\n'

In [178]:
emails_bodies = [
    "Olá! Esperamos que esteja bem. Gostaríamos de lembrá-lo(a) sobre a renovação do seu plano anual. Aproveite o desconto exclusivo até o final da semana!",
    "Prezada cliente, informamos que sua encomenda foi enviada e o código de rastreio já está disponível em sua conta. Agradecemos por comprar conosco!",
    "Caro aluno, as inscrições para o próximo módulo do curso de Programação Web estão abertas. Garanta sua vaga com 20% de desconto até sexta-feira.",
    "Bom dia! Temos o prazer de anunciar o lançamento da nova linha de produtos ecológicos. Sustentabilidade e qualidade em um só lugar!",
    "Olá! Notamos que você deixou alguns itens no carrinho. Finalize sua compra hoje e receba frete grátis em todo o Brasil.",
    "Prezado parceiro, estamos organizando um evento exclusivo de networking para profissionais da área. Sua presença será muito bem-vinda!",
    "Olá, tudo bem? Seu agendamento para a consulta médica foi confirmado para o dia 5 de novembro às 15h. Contamos com sua pontualidade!",
    "Caro usuário, detectamos uma tentativa de login em sua conta. Se não foi você, altere sua senha imediatamente por segurança.",
    "Olá! Aproveite nossa promoção relâmpago: até 50% de desconto em eletrônicos e acessórios. Somente hoje!",
    "Bom dia! Sua reserva no Hotel Paraíso está confirmada. Estamos ansiosos para recebê-lo e tornar sua estadia inesquecível.",
    "Prezada cliente, seu pagamento foi processado com sucesso. O comprovante segue em anexo. Obrigado pela preferência!",
    "Olá, participante! Agradecemos por se inscrever no Workshop de Inovação. Em breve você receberá o link para acessar o evento online.",
    "Boa tarde! Estamos contratando novos talentos para nossa equipe de marketing digital. Envie seu currículo até o dia 10/11.",
    "Olá! Seu pedido de suporte foi recebido. Nossa equipe entrará em contato em até 24 horas para auxiliá-lo.",
    "Prezado leitor, a nova edição da nossa revista já está disponível. Confira as matérias especiais sobre tendências do mercado.",
    "Olá! Parabéns! Você foi selecionado para o programa de fidelidade Gold. Aproveite benefícios exclusivos e descontos personalizados.",
    "Caro cliente, estamos atualizando nossa política de privacidade. Recomendamos que leia as novas condições em nosso site.",
    "Bom dia! Convidamos você para participar da nossa pesquisa de satisfação. Sua opinião é muito importante para nós.",
    "Olá! Chegou a hora de planejar suas próximas férias. Descubra pacotes incríveis com até 30% de desconto.",
    "Prezado(a), lembramos que o prazo para entrega do relatório trimestral é dia 31/10. Por favor, envie dentro do prazo para evitar penalidades."
]

In [179]:
def resumidor_de_emails(lista_de_emails):
    for numero, email in enumerate(lista_de_emails):
        resposta = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=f"""Vou te mandar o corpo de um e-mail. Quero que você o resuma em apenas uma linha,
                     passando o intuito daquele email. Segue o e-mail: {email}"""
            )
        print(f"E-mail: {numero + 1}: {resposta.text} ")
        # print("-" * 50 )
        print("_"* 5 )

In [180]:
resumidor_de_emails(emails_bodies)

E-mail: 1: Lembrete para renovar seu plano anual, aproveitando um desconto exclusivo e por tempo limitado.
_____
E-mail: 2: Seu pedido foi enviado e o código de rastreio já está disponível.
_____
E-mail: 3: Matricule-se no próximo módulo de Programação Web e aproveite 20% de desconto até sexta-feira.
_____
E-mail: 4: Anúncio do lançamento de uma nova linha de produtos ecológicos que combinam sustentabilidade e qualidade.
_____
E-mail: 5: O e-mail te incentiva a finalizar sua compra pendente, oferecendo frete grátis como benefício.
_____
E-mail: 6: Convite para um evento exclusivo de networking, onde sua presença é muito bem-vinda.
_____
E-mail: 7: Confirmação da sua consulta médica para 5 de novembro às 15h.
_____
E-mail: 8: O e-mail alerta sobre uma tentativa de login na sua conta e instrui a alterar a senha imediatamente por segurança, caso não a reconheça.
_____
E-mail: 9: Promoção relâmpago: até 50% de desconto em eletrônicos e acessórios, válida somente hoje.
_____
E-mail: 10: **Confirmação da sua reserva no Hotel Paraíso.**
_____

ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 8.759987709s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '8s'}]}}

In [181]:
!pip install -q groq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 2.3 MB/s eta 0:00:00

In [182]:
import os

from google.colab import userdata

In [183]:
os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

In [184]:
from groq import Groq

client_groq = Groq()

completion = client_groq.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
      {
        "role": "user",
        "content": "Quais países estão com déficit de contratação de AI Engineers ?"
      }
    ],
    temperature=1,  # 0: O menos criativo possível,   2: O mais criativo possível.
    max_completion_tokens=1024,
    top_p=1,
    reasoning_effort="medium",
    stream=True,
    stop=None
)

for chunk in completion:
    print(chunk.choices[0].delta.content or "", end="")

## Países que mais relataram **déficit de contratação de AI Engineers** (engenheiros de Inteligência Artificial)

| País | Fonte/Estudo | Principais causas do déficit | Estratégias adotadas / Oportunidades |
|------|--------------|------------------------------|--------------------------------------|
| **Estados Unidos** | LinkedIn 2023, “Global Talent Trends”; Gartner “Artificial‑Intelligence Workforce Forecast 2025” | 1) Crescimento explosivo de startups e grandes corporações <br>2) Falta de programas de graduação focados em IA <br>3) Alto custo de vida em hubs como SF, NYC | 1) Incentivos fiscais e bolsas de estudo (NIH, NSF) <br>2) Parcerias universidade‑indústria (ex.: MIT‑Harvard) <br>3) Programas de “AI Bootcamps” e re‑qualificação de profissionais |
| **Reino Unido** | Gartner 2024, “UK AI Talent Gap” | 1) Pós‑Brexit, restrição de vistos para talento estrangeiro <br>2) Concorrência de outros países com custos menores <br>3) Falta de especialização em deep‑learning em escolas técnicas | 1) Política “AI Talent Visa” (pioneiro na Europa) <br>2) Aumento de cursos de pós‑graduação em IA (Oxford, Cambridge) |
| **Canadá** | LinkedIn 2023 | 1) Demanda em Toronto, Vancouver <br>2) Sistema de imigração que favorece mas não garante posição de trabalho <br>3) Pouco investimento em centros de pesquisa de IA | 1) “Global Talent Stream” para profissionais de IA <br>2) Investimento em “AI Strategy” 2020‑2024 |
| **Alemanha** | McKinsey 2024, “AI Adoption in Europe” | 1) Tradicional foco em engenharia de manufatura, não em IA <br>2) Escassez de professores qualificados <br>3) Diferenças regionais (Bavaria > Renânia) | 1) Programa “Digital Hub” em Berlim e Munich <br>2) Bolsas de estudo “BMBF AI” |
| **França** | INSEE 2023 | 1) Falta de programas de pós‑graduação em IA <br>2) Dependência de talento estrangeiro <br>3) Burocracia para contratação de estrangeiros | 1) “AI for all” 2022 <br>2) Parcerias com empresas como Capgemini, Dassault‑Systèmes |
| **Singapura** | GovTech 2024 | 1) Baixa população (≈5,7M) <br>2) Alta concorrência por posições de alta tecnologia <br>3) Falta de professores de IA no sistema de ensino | 1) “AI School” na Nanyang Technological University <br>2) Incentivos de investimento estrangeiro |
| **Países Baixos** | Deloitte 2023 | 1) Alta demanda em fintech e logística <br>2) Falta de professores de IA em escolas técnicas | 1) Programa “AI Talent” 2023 <br>2) Colaboração com universidades de Delft e Utrecht |
| **Coreia do Sul** | Korea AI Association 2024 | 1) Concorrência com China e Japão <br>2) Falta de mão‑de‑obra especializada em IA | 1) “AI Human

# Operador de Resto

In [185]:
for n in range(11):
    if n % 2 == 0:
        print(n)  # Imprime números pares: 0, 2, 4, 6, 8, 10

0
2
4
6
8
10

In [186]:
lista = ['a', 'b', 'c', 'd']

len(lista)

4

In [187]:

for i in range(10):

    print(lista[i % len(lista)])  # Acessa sempre um índice válido na lista

a
b
c
d
a
b
c
d
a
b

# Leitura e Escrita de Arquivos

In [188]:
from google import genai

client = genai.Client()

In [189]:
def resumidor_de_emails(lista_de_emails):

    lista_de_resumos =[]

    for numero, email in enumerate(lista_de_emails):

        resposta = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=f"""Vou te mandar o corpo de um e-mail. Quero que você o resuma em apenas uma linha,
                     passando o intuito daquele email. Segue o e-mail: {email}"""
            )

        print(f"E-mail: {numero + 1}: {resposta.text} ")

        lista_de_resumos.append(f"E-mail: {numero + 1}: {resposta.text} ")

        print("-" * 50 )

    return lista_de_resumos

In [191]:
lista_resumos = resumidor_de_emails(emails_bodies)

E-mail: 1: Aqui está:

**Lembrete para renovar seu plano anual, aproveitando um desconto exclusivo.**
--------------------------------------------------
E-mail: 2: Notificar o cliente sobre o envio da sua encomenda e a disponibilidade do código de rastreio.
--------------------------------------------------
E-mail: 3: As inscrições para o próximo módulo de Programação Web estão abertas com 20% de desconto até sexta-feira.
--------------------------------------------------

ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 18.029145655s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '18s'}]}}

In [ ]:
lista_resumos

In [ ]:
with open("lista-de-resumos.txt", "w", encoding="utf-8") as arquivo:

    for resumo in lista_resumos:

        arquivo.write(resumo + "\n")
        #arquivo.writelines(lista_resumos)

In [ ]:
print(lista_resumos)

In [ ]:
with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:

    for linha in arquivo:
        print(linha)

In [ ]:
nova_lista_de_leitura = []

with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:

    for linha in arquivo:
        nova_lista_de_leitura.append(linha.strip())

In [ ]:
nova_lista_de_leitura

In [ ]:
conteudo = ""

with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:

    conteudo = arquivo.read()

In [ ]:
conteudo

In [ ]:
nova_lista_de_leitura_2 = []

with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:

    nova_lista_de_leitura_2 = arquivo.readlines()

In [ ]:
nova_lista_de_leitura_2

## Manipulando Dados com Pandas

In [193]:
import pandas as pd

In [194]:
# Imports for batching (removed)

# Batching Explanation (removed)

In [195]:
# Batched sentiment analysis code (removed)

In [197]:
df = pd.read_csv("/content/meu_csv.csv")

In [ ]:
df

       nome  media
0       Ana    7.5
1    Carlos    8.2
2   Beatriz    9.1
3     Diogo    6.8
4   Eduarda    5.9
5  Fernanda    8.5
6   Gustavo    7.3
7    Helena    9.5
8      Igor    6.1
9   Juliana    8.9

In [198]:
df.head()

      nome  media
0      Ana    7.5
1   Carlos    8.2
2  Beatriz    9.1
3    Diogo    6.8
4  Eduarda    5.9

In [199]:
df.head(7)

       nome  media
0       Ana    7.5
1    Carlos    8.2
2   Beatriz    9.1
3     Diogo    6.8
4   Eduarda    5.9
5  Fernanda    8.5
6   Gustavo    7.3

In [200]:
df.tail()

       nome  media
5  Fernanda    8.5
6   Gustavo    7.3
7    Helena    9.5
8      Igor    6.1
9   Juliana    8.9

Desafio:
1. Criar um arquivo .txt a partir de uma lista de perguntas vindas de uma lista em Python.
2. Ler as perguntas desse arquivo .txt e salvar em uma lista Python.
3. Obter as respostas de um LLM para cada uma.
4. SAlvar os resultados em um novo arquivo .csv
5. Ler o arquivo .csv usando Pandas.

In [201]:
# Step 1:
lista_10_perguntas = [
    "Qual é a lista de todos os filmes e seriados do personagem Batman ?",
    "Quantos bairros existem na cidade de Campinas em São Paulo ?",
    "Qual o tamnho da população de Campinas - SP ? ",
    "Quantos Shoppings Centers existem em Campinas - SP e quais são eles ?",
    "Quantas empresas de tecnologia existem em Campinas - SP e quais são elas ?",
    "Quais países no mundo estão atualmente, contratando mais profissionais em funções relacionadas a Inteligência Artificial ?",
    "Qual é a lista de todos os filmes e seriados do personagem Superman ?",
    "Quantos bairros existem na cidade de São Paulo em São Paulo ?",
    "Qual o tamnho da população de São Paulo - SP ? ",
    "Quantos Shoppings Centers existem em São Paulo - SP e quais são eles ?"
    ]

with open("perguntas.txt", "w", encoding="utf-8") as arquivo2:
    for pergunta in lista_10_perguntas:
        arquivo2.write(pergunta + "\n")

In [202]:
# Step 2:

lista_desafio = []

with open("perguntas.txt", "r", encoding="utf-8") as arquivo3:

    for linha in arquivo3:

        lista_desafio.append(linha.strip())

print(lista_desafio)

['Qual é a lista de todos os filmes e seriados do personagem Batman ?', 'Quantos bairros existem na cidade de Campinas em São Paulo ?', 'Qual o tamnho da população de Campinas - SP ?', 'Quantos Shoppings Centers existem em Campinas - SP e quais são eles ?', 'Quantas empresas de tecnologia existem em Campinas - SP e quais são elas ?', 'Quais países no mundo estão atualmente, contratando mais profissionais em funções relacionadas a Inteligência Artificial ?', 'Qual é a lista de todos os filmes e seriados do personagem Superman ?', 'Quantos bairros existem na cidade de São Paulo em São Paulo ?', 'Qual o tamnho da população de São Paulo - SP ?', 'Quantos Shoppings Centers existem em São Paulo - SP e quais são eles ?']

In [203]:

import os

from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('Gemini_API_Key')

In [204]:
from google import genai

client = genai.Client()

In [205]:

# Step 3:

lista_dicionario_respostas = []

for pergunta in lista_desafio:

    resposta = client.models.generate_content(
        model='gemini-2.5-flash',
        contents= f"Gere uma resposta muito sucinta para a pergunta: {pergunta}"
    )


    dicionario_respostas = {
        "pergunta": pergunta,
        "resposta": resposta.text
    }


    lista_dicionario_respostas.append(
        {
        "pergunta": pergunta,
        "resposta": resposta.text
        }
    )

ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 39.44299658s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '39s'}]}}

In [ ]:
lista_dicionario_respostas

In [ ]:
# Step 4:

with open ("respostas1.csv", "w", encoding="utf-8") as arquivo4:

    arquivo4.write("pergunta,resposta\n")

    for pergunta_dict in lista_dicionario_respostas:
        # Remove internal newlines and enclose response in quotes
        resposta_formatada = pergunta_dict["resposta"].replace('\n', ' ').replace("\"", "\"\"")
        arquivo4.write(f'"{pergunta_dict["pergunta"]}","{resposta_formatada}"\n')

In [ ]:
# Step 4: (Usando PANDAS)

df_perguntas_e_respostas = pd.DataFrame(lista_dicionario_respostas)

In [ ]:
df_perguntas_e_respostas

In [ ]:
df_perguntas_e_respostas.to_csv(
    "respostas2.csv",
    index=False,
    encoding="utf-8"
)

In [ ]:
df_perguntas_e_respostas

In [ ]:
# Step 5:

novo_df = pd.read_csv("respostas2.csv")

In [ ]:
novo_df

In [206]:
import pandas as pd
import numpy as np

# Generating 50 rows of data
num_rows = 50

data = {
    'Nome do produto': [f'Produto_{i+1}' for i in range(num_rows)],
    'Categoria do produto': np.random.choice(['Eletrônicos', 'Acessórios', 'Informática', 'Periféricos', 'Componentes'], size=num_rows).tolist(),
    'Preço do produto': np.random.uniform(10.00, 2000.00, size=num_rows).round(2).tolist(),
    'Quantidade vendida': np.random.randint(1, 200, size=num_rows).tolist(),
    'Avaliação do produto': np.random.uniform(1.0, 5.0, size=num_rows).round(1).tolist()
}

df_produtos = pd.DataFrame(data)

display(df_produtos)

,Nome do produto,Categoria do produto,Preço do produto,Quantidade vendida,Avaliação do produto
0,Produto_1,Eletrônicos,1769.68,195,2.0
1,Produto_2,Periféricos,1720.87,140,2.8
2,Produto_3,Eletrônicos,1928.22,131,2.4
3,Produto_4,Informática,667.42,56,4.9
4,Produto_5,Eletrônicos,736.75,130,3.6
5,Produto_6,Eletrônicos,418.11,130,2.7
6,Produto_7,Componentes,1781.08,183,2.5
7,Produto_8,Periféricos,488.18,191,4.2
8,Produto_9,Acessórios,1909.39,184,4.6
9,Produto_10,Componentes,79.06,104,4.2
10,Produto_11,Acessórios,1629.09,48,3.0
11,Produto_12,Eletrônicos,766.26,76,2.6
12,Produto_13,Informática,1555.46,140,4.7
13,Produto_14,Acessórios,1220.00,129,2.6
14,Produto_15,Informática,277.10,149,3.8
15,Produto_16,Periféricos,1111.74,184,2.9
16,Produto_17,Informática,1119.87,196,5.0
17,Produto_18,Acessórios,1301.91,191,1.0
18,Produto_19,Componentes,1968.40,198,3.1
19,Produto_20,Acessórios,1792.40,108,3.1
20,Produto_21,Componentes,17.04,72,1.1
21,Produto_22,Eletrônicos,664.19,60,4.4
22,Produto_23,Eletrônicos,952.85,170,1.8
23,Produto_24,Eletrônicos,572.10,54,1.9
24,Produto_25,Eletrônicos,1877.26,167,3.3
25,Produto_26,Componentes,351.49,81,3.7
26,Produto_27,Informática,1198.57,64,4.0
27,Produto_28,Acessórios,1924.68,107,4.3
28,Produto_29,Acessórios,538.70,161,2.0
29,Produto_30,Informática,1370.82,183,1.1
30,Produto_31,Componentes,926.85,129,1.9
31,Produto_32,Acessórios,1786.38,107,3.2
32,Produto_33,Eletrônicos,254.53,93,5.0
33,Produto_34,Acessórios,1896.12,182,1.7
34,Produto_35,Componentes,475.94,180,2.3
35,Produto_36,Informática,409.00,172,1.0
36,Produto_37,Componentes,1190.66,12,4.1
37,Produto_38,Periféricos,1335.93,80,1.9
38,Produto_39,Acessórios,1828.74,183,4.2
39,Produto_40,Acessórios,752.06,84,3.4
40,Produto_41,Informática,934.00,189,3.7
41,Produto_42,Componentes,346.50,80,4.2
42,Produto_43,Componentes,1215.08,158,3.0
43,Produto_44,Acessórios,797.47,129,3.5
44,Produto_45,Periféricos,73.64,131,4.9
45,Produto_46,Componentes,827.22,104,3.4
46,Produto_47,Informática,1471.35,79,4.8
47,Produto_48,Acessórios,1282.85,181,3.8
48,Produto_49,Acessórios,1719.11,109,3.3
49,Produto_50,Componentes,1712.81,49,3.1

In [207]:
df_produtos["Categoria do produto"]

0     Eletrônicos
1     Periféricos
2     Eletrônicos
3     Informática
4     Eletrônicos
5     Eletrônicos
6     Componentes
7     Periféricos
8      Acessórios
9     Componentes
10     Acessórios
11    Eletrônicos
12    Informática
13     Acessórios
14    Informática
15    Periféricos
16    Informática
17     Acessórios
18    Componentes
19     Acessórios
20    Componentes
21    Eletrônicos
22    Eletrônicos
23    Eletrônicos
24    Eletrônicos
25    Componentes
26    Informática
27     Acessórios
28     Acessórios
29    Informática
30    Componentes
31     Acessórios
32    Eletrônicos
33     Acessórios
34    Componentes
35    Informática
36    Componentes
37    Periféricos
38     Acessórios
39     Acessórios
40    Informática
41    Componentes
42    Componentes
43     Acessórios
44    Periféricos
45    Componentes
46    Informática
47     Acessórios
48     Acessórios
49    Componentes
Name: Categoria do produto, dtype: object

In [208]:
df_produtos["Categoria do produto"].unique()

array(['Eletrônicos', 'Periféricos', 'Informática', 'Componentes',
       'Acessórios'], dtype=object)

In [209]:
set(df_produtos["Categoria do produto"])

{'Acessórios', 'Componentes', 'Eletrônicos', 'Informática', 'Periféricos'}

## Filtrando elementos de um Dataframe Pandas

In [210]:
df_produtos["Categoria do produto"] == "Informática"

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14     True
15    False
16     True
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26     True
27    False
28    False
29     True
30    False
31    False
32    False
33    False
34    False
35     True
36    False
37    False
38    False
39    False
40     True
41    False
42    False
43    False
44    False
45    False
46     True
47    False
48    False
49    False
Name: Categoria do produto, dtype: bool

In [211]:
df_produtos[df_produtos["Categoria do produto"] == "Informática"]

,Nome do produto,Categoria do produto,Preço do produto,Quantidade vendida,Avaliação do produto
3,Produto_4,Informática,667.42,56,4.9
12,Produto_13,Informática,1555.46,140,4.7
14,Produto_15,Informática,277.10,149,3.8
16,Produto_17,Informática,1119.87,196,5.0
26,Produto_27,Informática,1198.57,64,4.0
29,Produto_30,Informática,1370.82,183,1.1
35,Produto_36,Informática,409.00,172,1.0
40,Produto_41,Informática,934.00,189,3.7
46,Produto_47,Informática,1471.35,79,4.8

In [212]:
df_produtos[df_produtos["Avaliação do produto"] < 2.0 ]

,Nome do produto,Categoria do produto,Preço do produto,Quantidade vendida,Avaliação do produto
17,Produto_18,Acessórios,1301.91,191,1.0
20,Produto_21,Componentes,17.04,72,1.1
22,Produto_23,Eletrônicos,952.85,170,1.8
23,Produto_24,Eletrônicos,572.10,54,1.9
29,Produto_30,Informática,1370.82,183,1.1
30,Produto_31,Componentes,926.85,129,1.9
33,Produto_34,Acessórios,1896.12,182,1.7
35,Produto_36,Informática,409.00,172,1.0
37,Produto_38,Periféricos,1335.93,80,1.9

In [213]:
df_produtos.shape

(50, 5)

In [214]:
filtro_menor_2 = df_produtos["Avaliação do produto"] < 2.0

filtro_categoria_produto = df_produtos["Categoria do produto"] == "Informática"

In [215]:
filtro_menor_2

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18    False
19    False
20     True
21    False
22     True
23     True
24    False
25    False
26    False
27    False
28    False
29     True
30     True
31    False
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: Avaliação do produto, dtype: bool

In [216]:
filtro_categoria_produto

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14     True
15    False
16     True
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26     True
27    False
28    False
29     True
30    False
31    False
32    False
33    False
34    False
35     True
36    False
37    False
38    False
39    False
40     True
41    False
42    False
43    False
44    False
45    False
46     True
47    False
48    False
49    False
Name: Categoria do produto, dtype: bool

In [217]:
filtro_categoria_produto.shape

(50,)

In [218]:
filtro_menor_2.shape

(50,)

In [219]:
df_produtos[(df_produtos["Categoria do produto"] == "Eletrônicos") & (df_produtos["Preço do produto"] >= 550.0)]

,Nome do produto,Categoria do produto,Preço do produto,Quantidade vendida,Avaliação do produto
0,Produto_1,Eletrônicos,1769.68,195,2.0
2,Produto_3,Eletrônicos,1928.22,131,2.4
4,Produto_5,Eletrônicos,736.75,130,3.6
11,Produto_12,Eletrônicos,766.26,76,2.6
21,Produto_22,Eletrônicos,664.19,60,4.4
22,Produto_23,Eletrônicos,952.85,170,1.8
23,Produto_24,Eletrônicos,572.10,54,1.9
24,Produto_25,Eletrônicos,1877.26,167,3.3

In [220]:
df_produtos.iloc[15]

Nome do produto          Produto_16
Categoria do produto    Periféricos
Preço do produto            1111.74
Quantidade vendida              184
Avaliação do produto            2.9
Name: 15, dtype: object

In [221]:
df_produtos.iloc[43:]

,Nome do produto,Categoria do produto,Preço do produto,Quantidade vendida,Avaliação do produto
43,Produto_44,Acessórios,797.47,129,3.5
44,Produto_45,Periféricos,73.64,131,4.9
45,Produto_46,Componentes,827.22,104,3.4
46,Produto_47,Informática,1471.35,79,4.8
47,Produto_48,Acessórios,1282.85,181,3.8
48,Produto_49,Acessórios,1719.11,109,3.3
49,Produto_50,Componentes,1712.81,49,3.1

In [222]:
df_produtos.loc[15]

Nome do produto          Produto_16
Categoria do produto    Periféricos
Preço do produto            1111.74
Quantidade vendida              184
Avaliação do produto            2.9
Name: 15, dtype: object

In [223]:
df_produtos_com_indice = df_produtos.set_index("Nome do produto")
#display(df_produtos_indexed)
df_produtos_com_indice

,Categoria do produto,Preço do produto,Quantidade vendida,Avaliação do produto
Nome do produto,,,,
Produto_1,Eletrônicos,1769.68,195,2.0
Produto_2,Periféricos,1720.87,140,2.8
Produto_3,Eletrônicos,1928.22,131,2.4
Produto_4,Informática,667.42,56,4.9
Produto_5,Eletrônicos,736.75,130,3.6
Produto_6,Eletrônicos,418.11,130,2.7
Produto_7,Componentes,1781.08,183,2.5
Produto_8,Periféricos,488.18,191,4.2
Produto_9,Acessórios,1909.39,184,4.6
Produto_10,Componentes,79.06,104,4.2
Produto_11,Acessórios,1629.09,48,3.0
Produto_12,Eletrônicos,766.26,76,2.6
Produto_13,Informática,1555.46,140,4.7
Produto_14,Acessórios,1220.00,129,2.6
Produto_15,Informática,277.10,149,3.8
Produto_16,Periféricos,1111.74,184,2.9
Produto_17,Informática,1119.87,196,5.0
Produto_18,Acessórios,1301.91,191,1.0
Produto_19,Componentes,1968.40,198,3.1
Produto_20,Acessórios,1792.40,108,3.1
Produto_21,Componentes,17.04,72,1.1
Produto_22,Eletrônicos,664.19,60,4.4
Produto_23,Eletrônicos,952.85,170,1.8
Produto_24,Eletrônicos,572.10,54,1.9
Produto_25,Eletrônicos,1877.26,167,3.3
Produto_26,Componentes,351.49,81,3.7
Produto_27,Informática,1198.57,64,4.0
Produto_28,Acessórios,1924.68,107,4.3
Produto_29,Acessórios,538.70,161,2.0
Produto_30,Informática,1370.82,183,1.1
Produto_31,Componentes,926.85,129,1.9
Produto_32,Acessórios,1786.38,107,3.2
Produto_33,Eletrônicos,254.53,93,5.0
Produto_34,Acessórios,1896.12,182,1.7
Produto_35,Componentes,475.94,180,2.3
Produto_36,Informática,409.00,172,1.0
Produto_37,Componentes,1190.66,12,4.1
Produto_38,Periféricos,1335.93,80,1.9
Produto_39,Acessórios,1828.74,183,4.2
Produto_40,Acessórios,752.06,84,3.4
Produto_41,Informática,934.00,189,3.7
Produto_42,Componentes,346.50,80,4.2
Produto_43,Componentes,1215.08,158,3.0
Produto_44,Acessórios,797.47,129,3.5
Produto_45,Periféricos,73.64,131,4.9
Produto_46,Componentes,827.22,104,3.4
Produto_47,Informática,1471.35,79,4.8
Produto_48,Acessórios,1282.85,181,3.8
Produto_49,Acessórios,1719.11,109,3.3
Produto_50,Componentes,1712.81,49,3.1

In [224]:
df_produtos_com_indice.loc["Produto_15"]

Categoria do produto    Informática
Preço do produto              277.1
Quantidade vendida              149
Avaliação do produto            3.8
Name: Produto_15, dtype: object

In [225]:
df_produtos_com_indice.loc["Produto_15":"Produto_20"]

,Categoria do produto,Preço do produto,Quantidade vendida,Avaliação do produto
Nome do produto,,,,
Produto_15,Informática,277.10,149,3.8
Produto_16,Periféricos,1111.74,184,2.9
Produto_17,Informática,1119.87,196,5.0
Produto_18,Acessórios,1301.91,191,1.0
Produto_19,Componentes,1968.40,198,3.1
Produto_20,Acessórios,1792.40,108,3.1

In [226]:
df_produtos_com_indice.loc["Produto_45":]

,Categoria do produto,Preço do produto,Quantidade vendida,Avaliação do produto
Nome do produto,,,,
Produto_45,Periféricos,73.64,131,4.9
Produto_46,Componentes,827.22,104,3.4
Produto_47,Informática,1471.35,79,4.8
Produto_48,Acessórios,1282.85,181,3.8
Produto_49,Acessórios,1719.11,109,3.3
Produto_50,Componentes,1712.81,49,3.1

In [227]:
df_produtos_com_indice.loc["Produto_45","Preço do produto"]

np.float64(73.64)

In [228]:
eletronicos = df_produtos_com_indice[df_produtos_com_indice["Categoria do produto"] == "Eletrônicos"]

In [229]:
df_produtos_com_indice.loc[eletronicos.index, ["Preço do produto", "Quantidade vendida"]]

                 Preço do produto  Quantidade vendida
Nome do produto
Produto_1                 1769.68                 195
Produto_3                 1928.22                 131
Produto_5                  736.75                 130
Produto_6                  418.11                 130
Produto_12                 766.26                  76
Produto_22                 664.19                  60
Produto_23                 952.85                 170
Produto_24                 572.10                  54
Produto_25                1877.26                 167
Produto_33                 254.53                  93

In [230]:
df_produtos_com_indice.loc["Produto_45":]

,Categoria do produto,Preço do produto,Quantidade vendida,Avaliação do produto
Nome do produto,,,,
Produto_45,Periféricos,73.64,131,4.9
Produto_46,Componentes,827.22,104,3.4
Produto_47,Informática,1471.35,79,4.8
Produto_48,Acessórios,1282.85,181,3.8
Produto_49,Acessórios,1719.11,109,3.3
Produto_50,Componentes,1712.81,49,3.1

In [231]:
brinquedos = df_produtos_com_indice[df_produtos_com_indice["Categoria do produto"] == "Brinquedos"]
df_produtos_com_indice.loc[brinquedos.index, "Categoria do produto"] = "Infanto-juvenil"

In [232]:
df_produtos_com_indice

,Categoria do produto,Preço do produto,Quantidade vendida,Avaliação do produto
Nome do produto,,,,
Produto_1,Eletrônicos,1769.68,195,2.0
Produto_2,Periféricos,1720.87,140,2.8
Produto_3,Eletrônicos,1928.22,131,2.4
Produto_4,Informática,667.42,56,4.9
Produto_5,Eletrônicos,736.75,130,3.6
Produto_6,Eletrônicos,418.11,130,2.7
Produto_7,Componentes,1781.08,183,2.5
Produto_8,Periféricos,488.18,191,4.2
Produto_9,Acessórios,1909.39,184,4.6
Produto_10,Componentes,79.06,104,4.2
Produto_11,Acessórios,1629.09,48,3.0
Produto_12,Eletrônicos,766.26,76,2.6
Produto_13,Informática,1555.46,140,4.7
Produto_14,Acessórios,1220.00,129,2.6
Produto_15,Informática,277.10,149,3.8
Produto_16,Periféricos,1111.74,184,2.9
Produto_17,Informática,1119.87,196,5.0
Produto_18,Acessórios,1301.91,191,1.0
Produto_19,Componentes,1968.40,198,3.1
Produto_20,Acessórios,1792.40,108,3.1
Produto_21,Componentes,17.04,72,1.1
Produto_22,Eletrônicos,664.19,60,4.4
Produto_23,Eletrônicos,952.85,170,1.8
Produto_24,Eletrônicos,572.10,54,1.9
Produto_25,Eletrônicos,1877.26,167,3.3
Produto_26,Componentes,351.49,81,3.7
Produto_27,Informática,1198.57,64,4.0
Produto_28,Acessórios,1924.68,107,4.3
Produto_29,Acessórios,538.70,161,2.0
Produto_30,Informática,1370.82,183,1.1
Produto_31,Componentes,926.85,129,1.9
Produto_32,Acessórios,1786.38,107,3.2
Produto_33,Eletrônicos,254.53,93,5.0
Produto_34,Acessórios,1896.12,182,1.7
Produto_35,Componentes,475.94,180,2.3
Produto_36,Informática,409.00,172,1.0
Produto_37,Componentes,1190.66,12,4.1
Produto_38,Periféricos,1335.93,80,1.9
Produto_39,Acessórios,1828.74,183,4.2
Produto_40,Acessórios,752.06,84,3.4
Produto_41,Informática,934.00,189,3.7
Produto_42,Componentes,346.50,80,4.2
Produto_43,Componentes,1215.08,158,3.0
Produto_44,Acessórios,797.47,129,3.5
Produto_45,Periféricos,73.64,131,4.9
Produto_46,Componentes,827.22,104,3.4
Produto_47,Informática,1471.35,79,4.8
Produto_48,Acessórios,1282.85,181,3.8
Produto_49,Acessórios,1719.11,109,3.3
Produto_50,Componentes,1712.81,49,3.1

Desafio:
1. Carregar um arquivo .csv com feedback de clientes ("reviews.csv")
2. Usar um LLM para classificar o sentimento de cada feedback (Positivo, Negativo, Neutro)
3. Adicionar uma nova coluna com essa classificação ao DataFrame.

In [233]:
# Step 1
df_reviews = pd.read_csv("/content/reviews.csv")

In [234]:
df_reviews

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0
5,A2Q3ICGWZLY3JJ,B007WTAJTO,98020,"It works, but file writes are a bit slower tha...",1384905600,20/11/2013,383,0,0
6,AF24M1HKIZ7QC,B007WTAJTO,"Abdulrahman J. Alrashed ""dr34m3r""","I bought 2 of those SanDisk 32 GB microSD , us...",1375488000,08/03/2013,640,0,0
7,A1KIF9Z5VFPH7H,B007WTAJTO,"Abel Feliciano ""Ace Master""",The memory card is an excellent condition and ...,1347321600,09/11/2012,759,0,0
8,A1FKE13D77L3Y3,B007WTAJTO,Abraham Arturo Meza Marin,I bougth this micro SD card after some trubles...,1361232000,19/02/2013,657,0,0
9,A1X1FX3NSOFCT3,B007WTAJTO,"Abused Commuter ""abused_commuter""",Ordered this for a Galaxy S3. Lasted a few mo...,1374278400,20/07/2013,506,0,1
10,A3RV1L35IPTV61,B007WTAJTO,abushaheed,more like 8mb/s in my Note 10.1 and that's usi...,1357430400,01/06/2013,555,0,0
11,A2RJ7DAL63MN1F,B007WTAJTO,Ace of Sevens,"I used this for a few months in my phone, then...",1391126400,31/01/2014,311,0,0
12,A3IJIFZ5HH819V,B007WTAJTO,A. Cho,"everything about it was great, except for the ...",1373414400,07/10/2013,427,0,0
13,A1R0JMNRV7HVQM,B007WTAJTO,ACZ,Used in my phone it's plenty fast and works ju...,1383609600,11/05/2013,576,0,0
14,APAEBFIM1588A,B007WTAJTO,"Adam Wright ""Electrical Engineer""",This card advertises itself as UHS1 but it's a...,1378684800,09/09/2013,455,1,1
15,A1JOXGZH55JMHW,B007WTAJTO,A. Hejazi,I bought this SD card for my android phone thi...,1386806400,12/12/2013,361,0,0
16,A35NR2GQWMQ31K,B007WTAJTO,ahhsimon,good card. work as describes. haven't had any ...,1391644800,02/06/2014,189,0,0
17,A1N7LGUPJWWQS9,B007WTAJTO,A.J. Matheson,I got this because I just couldn't pass up the...,1353888000,26/11/2012,742,0,0
18,A28CTDM7OP0RAR,B007WTAJTO,Alan,It works but the actual R/W speeds are 18/8 MB...,1395705600,25/03/2014,258,0,0
19,A1NA2JGI3GNDN2,B007WTAJTO,Albert,Does it's job and fairly cheap for what it's w...,1399161600,05/04/2014,247,0,0
20,A3PCW69GQK8R38,B007WTAJTO,Alejandro Hernndez,Still don't feel is very fast or is just my ph...,1391385600,02/03/2014,281,0,0
21,A1UM44ILLZCEI1,B007WTAJTO,Aleksandar Milivojevic,I bought 64GB version of the card to use with ...,1364947200,04/03/2013,644,1,1
22,A2T71JNR3C2DY1,B007WTAJTO,"Ali Etezadkhah ""Ali""",I have an old SanDisk SD card that still works...,1371859200,22/06/2013,534,0,0
23,A87U7LY9OKZNY,B007WTAJTO,A. Liu,Used it in my Galaxy Note 2 for the past 16 mo...,1398988800,05/02/2014,306,0,0
24,A277QWS5WF6DWI,B007WTAJTO,Alton L Spencer,Worked great in my galaxy s4--until it didn't ...,1401148800,27/05/2014,195,0,0
25,A1WWPAQ1DD6BQC,B007WTAJTO,A. Marte,I bought this on August of 2013. As of April ...,1403654400,25/06/2014,166,1,1
26,A3FY6V3LXP8SSL,B007WTAJTO,"Amazon Customer ""fiction buff""",So this product is a large disappointment...bo...,1349136000,10/02/2012,1032,0,0
27,A3DXCQV1U6QLTS,B007WTAJTO,Amazon Customer,I will keep it short and sweet for potential b...,1360195200,02/07/2013,524,0,0
28,A3R2TY7PFN9VSM,B007WTAJTO,Amazon Customer,"The package arrived on time, it's very well pa...",1375660800,08/05/2013,579,0,0
29,A1FZKP9XTKMALD,B007WTAJTO,Amazon Customer,"Does what it says. Hasn't broken yet, and I ho...",1375401600,08/02/2013,668,0,1
30,A308JP3BK4VAL7,B007WTAJTO,Amazon Customer,Thus microSD card worked fine for a year in my...,1398643200,28/04/2014,224,0,3
31,A392ZR68AKLDCK,B007WTAJTO,"Amazon Customer ""Music Fan""","I think this is probably a fine product, but i...",1374796800,26/07/2013,500,1,1
32,A2DQ2U5BYIXNUJ,B007WTAJTO,"Amazon Customer ""PawsitivelySafe""",I have two of these and use them for my Galazy...,1387152000,16/12/2013,357,0,0
33,A14D2PS27PI3FM,B007WTAJTO,Amazon Fan,I join the long list of customers who have had...,1359936000,02/04/2013,615,1,2
34,A1Z7FZP81N8CDU,B007WTAJTO,Amazon Shopper,"I do not get the advertised speed of 30MB/s, m...",1394755200,14/03/2014,269,0,1
35,A1T8FVB93QQNOM,B007WTAJTO,Andrew M. Swiatek,the micro sd works great as described. but bew...,1372464000,29/06/2013,527,0,0
36,A3K1JZPUXSADRJ,B007WTAJTO,anonomous,than i expected. I don't know if it would kill...,1362182400,03/02/2013,673,0,2
37,A1D07XDTMWV0A5,B007WTAJTO,"A. Shieh ""eff.org""","Reliable and inexpensive. However, it's quite ...",1385769600,30/11/2013,373,0,0
38,A1HKW2TELCHGLL,B007WTAJTO,astraelraen,I bought this primarily to use in my Surface P...,1391040000,30/01/2014,312,0,0
39,A3P86Z2D81VLYV,B007WTAJTO,"Zeality ""N2iT""",I really don't know what to think about this I...,1396137600,30/03/2014,253,0,0

In [235]:
df_reviews.head()

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0

In [236]:

#Step2

lista_de_analises_de_sentimentos = []

coluna_de_reviews = df_reviews['reviewText']

for review_numero, resenha in enumerate(coluna_de_reviews):

    resposta = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=f"""Você irá analisar a resenha que eu te mandarei abaixo, e retorna com uma análise de sentimento.
                     Você deve responder APENAS com uma das seguintes palavras: 'Positiva', 'Negativa'ou 'Neutra',
                     indicando o sentimento relativo aquela resenha específica.
                     Exemplos:
                     'Eu adorei esse procuto'-> Positiva
                     'Gostei, mas não é nada de especial'-> Neutra
                     'Odiei esse produto' -> Negativa

                     Segue a resenha a ser analisadaa: {resenha}"""
)

    lista_de_analises_de_sentimentos.append(resposta.text)

    print(f"Resenha {review_numero}: '{resenha}' -> Sentimento: {resposta.text}")

ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 18.34762637s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '18s'}]}}

In [237]:
lista_de_analises_de_sentimentos

[]

In [239]:
# Step3:
df_reviews["Análises de Sentimentos"] = lista_de_analises_de_sentimentos

ValueError: Length of values (0) does not match length of index (40)

In [ ]:
df_reviews

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote,sentimento_gemini
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0,Erro na API
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0,Erro na API
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0,Erro na API
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0,Erro na API
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0,Erro na API
5,A2Q3ICGWZLY3JJ,B007WTAJTO,98020,"It works, but file writes are a bit slower tha...",1384905600,20/11/2013,383,0,0,Erro na API
6,AF24M1HKIZ7QC,B007WTAJTO,"Abdulrahman J. Alrashed ""dr34m3r""","I bought 2 of those SanDisk 32 GB microSD , us...",1375488000,08/03/2013,640,0,0,Erro na API
7,A1KIF9Z5VFPH7H,B007WTAJTO,"Abel Feliciano ""Ace Master""",The memory card is an excellent condition and ...,1347321600,09/11/2012,759,0,0,Erro na API
8,A1FKE13D77L3Y3,B007WTAJTO,Abraham Arturo Meza Marin,I bougth this micro SD card after some trubles...,1361232000,19/02/2013,657,0,0,Erro na API
9,A1X1FX3NSOFCT3,B007WTAJTO,"Abused Commuter ""abused_commuter""",Ordered this for a Galaxy S3. Lasted a few mo...,1374278400,20/07/2013,506,0,1,Erro na API
10,A3RV1L35IPTV61,B007WTAJTO,abushaheed,more like 8mb/s in my Note 10.1 and that's usi...,1357430400,01/06/2013,555,0,0,Erro na API
11,A2RJ7DAL63MN1F,B007WTAJTO,Ace of Sevens,"I used this for a few months in my phone, then...",1391126400,31/01/2014,311,0,0,Erro na API
12,A3IJIFZ5HH819V,B007WTAJTO,A. Cho,"everything about it was great, except for the ...",1373414400,07/10/2013,427,0,0,Erro na API
13,A1R0JMNRV7HVQM,B007WTAJTO,ACZ,Used in my phone it's plenty fast and works ju...,1383609600,11/05/2013,576,0,0,Erro na API
14,APAEBFIM1588A,B007WTAJTO,"Adam Wright ""Electrical Engineer""",This card advertises itself as UHS1 but it's a...,1378684800,09/09/2013,455,1,1,Erro na API
15,A1JOXGZH55JMHW,B007WTAJTO,A. Hejazi,I bought this SD card for my android phone thi...,1386806400,12/12/2013,361,0,0,Erro na API
16,A35NR2GQWMQ31K,B007WTAJTO,ahhsimon,good card. work as describes. haven't had any ...,1391644800,02/06/2014,189,0,0,Erro na API
17,A1N7LGUPJWWQS9,B007WTAJTO,A.J. Matheson,I got this because I just couldn't pass up the...,1353888000,26/11/2012,742,0,0,Erro na API
18,A28CTDM7OP0RAR,B007WTAJTO,Alan,It works but the actual R/W speeds are 18/8 MB...,1395705600,25/03/2014,258,0,0,Erro na API
19,A1NA2JGI3GNDN2,B007WTAJTO,Albert,Does it's job and fairly cheap for what it's w...,1399161600,05/04/2014,247,0,0,Erro na API
20,A3PCW69GQK8R38,B007WTAJTO,Alejandro Hernndez,Still don't feel is very fast or is just my ph...,1391385600,02/03/2014,281,0,0,Erro na API
21,A1UM44ILLZCEI1,B007WTAJTO,Aleksandar Milivojevic,I bought 64GB version of the card to use with ...,1364947200,04/03/2013,644,1,1,Erro na API
22,A2T71JNR3C2DY1,B007WTAJTO,"Ali Etezadkhah ""Ali""",I have an old SanDisk SD card that still works...,1371859200,22/06/2013,534,0,0,Erro na API
23,A87U7LY9OKZNY,B007WTAJTO,A. Liu,Used it in my Galaxy Note 2 for the past 16 mo...,1398988800,05/02/2014,306,0,0,Erro na API
24,A277QWS5WF6DWI,B007WTAJTO,Alton L Spencer,Worked great in my galaxy s4--until it didn't ...,1401148800,27/05/2014,195,0,0,Erro na API
25,A1WWPAQ1DD6BQC,B007WTAJTO,A. Marte,I bought this on August of 2013. As of April ...,1403654400,25/06/2014,166,1,1,Erro na API
26,A3FY6V3LXP8SSL,B007WTAJTO,"Amazon Customer ""fiction buff""",So this product is a large disappointment...bo...,1349136000,10/02/2012,1032,0,0,Erro na API
27,A3DXCQV1U6QLTS,B007WTAJTO,Amazon Customer,I will keep it short and sweet for potential b...,1360195200,02/07/2013,524,0,0,Erro na API
28,A3R2TY7PFN9VSM,B007WTAJTO,Amazon Customer,"The package arrived on time, it's very well pa...",1375660800,08/05/2013,579,0,0,Erro na API
29,A1FZKP9XTKMALD,B007WTAJTO,Amazon Customer,"Does what it says. Hasn't broken yet, and I ho...",1375401600,08/02/2013,668,0,1,Erro na API
30,A308JP3BK4VAL7,B007WTAJTO,Amazon Customer,Thus microSD card worked fine for a year in my...,1398643200,28/04/2014,224,0,3,Erro na API
31,A392ZR68AKLDCK,B007WTAJTO,"Amazon Customer ""Music Fan""","I think this is probably a fine product, but i...",1374796800,26/07/2013,500,1,1,Erro na API
32,A2DQ2U5BYIXNUJ,B007WTAJTO,"Amazon Customer ""PawsitivelySafe""",I have two of these and use them for my Galazy...,1387152000,16/12/2013,357,0,0,Erro na API
33,A14D2PS27PI3FM,B007WTAJTO,Amazon Fan,I join the long list of customers who have had...,1359936000,02/04/2013,615,1,2,Erro na API
34,A1Z7FZP81N8CDU,B007WTAJTO,Amazon Shopper,"I do not get the advertised speed of 30MB/s, m...",1394755200,14/03/2014,269,0,1,Erro na API
35,A1T8FVB93QQNOM,B007WTAJTO,Andrew M. Swiatek,the micro sd works great as described. but bew...,1372464000,29/06/2013,527,0,0,Erro na API
36,A3K1JZPUXSADRJ,B007WTAJTO,anonomous,than i expected. I don't know if it would kill...,1362182400,03/02/2013,673,0,2,Erro na API
37,A1D07XDTMWV0A5,B007WTAJTO,"A. Shieh ""eff.org""","Reliable and inexpensive. However, it's quite ...",1385769600,30/11/2013,373,0,0,Erro na API
38,A1HKW2TELCHGLL,B007WTAJTO,astraelraen,I bought this primarily to use in my Surface P...,1391040000,30/01/2014,312,0,0,Erro na API
39,A3P86Z2D81VLYV,B007WTAJTO,"Zeality ""N2iT""",I really don't know what to think about this I...,1396137600,30/03/2014,253,0,0,Erro na API

## Try  /  Except  /  Finally

In [238]:
try:
    pegando_algo = int(input("Digite a sua idade: "))

    # pessoas = 6
    # pessoas2 = "Mário, João, Sílvia, Maria"
    # pessoas + pessoas2

    magica = 25 / pegando_algo
    print(magica)

except ValueError as ve :
    print("Você não digitou um número inteiro válido")
    print("Detalhes do erro:", ve)
except TypeError as te :
    print("Você não pode somar um número inteiro com uma string")
except Exception as e :
    print("Detalhes do erro: \n", e)
finally:
    print("Finalizei o processo.")

Digite a sua idade: 500
0.05
Finalizei o processo.

In [ ]:
df_reviews_negativas = df_reviews[df_reviews["Análises de Sentimentos"] == "Negativa"]

df_reviews_negativas

In [ ]:
df_reviews_negativas.shape

In [ ]:
resenhas_negativas = df_reviews_negativas["reviewText"]

resenhas_negativas

In [ ]:
resenhas_negativas_unidas = "#####".join(resenhas_negativas)

In [ ]:
resposta_de_categorias = client.models.generate_content(
    model='gemini-2.5-flash',
    contents=f"""Você é um analista de dados. Vou te passar muitas resenhas negativas de análises de um produto,
              separadas por '#####' e eu quero que você encontre 5 categorias diferentes
              para os tipos de reclamações. Quero que você me retorne as 5 categorias.
              Cada categoria deve ser definida por apenas uma palavra.
              Não escreva nada mais além das 5 categorias.
              Quero que elas sejam retornadas separadas por vírgula e em letra minúscula e sem acentos gráficos.

              Exemplo: 'eletrônicos, roupas, alimentas, viagens, brinquedos'

              Aqui estão as resenhas negativas: {resenhas_negativas_unidas}"""
)

categorias = resposta_de_categorias.text

print(categorias)

In [ ]:
lista_de_categorias = categorias.split(", ")

lista_de_categorias

In [ ]:
dicionario_de_resenhas_classificadas = client.models.generate_content(
    model='gemini-2.5-flash',
    contents=f"""Você é um analista de dados. Vou te passar muitas resenhas negativas de análises de um produto,
              separadas por '#####' e eu quero que você encontre 5 categorias diferentes
              para os tipos de reclamações.
              Cada categoria deve ser definida por apenas uma palavra.
              Quero que elas sejam retornadas separadas por vírgula e em letra minúscula e sem acentos gráficos.

              Depois, eu quero que você me retorne APENAS um texto no formato JSON, contendo 3 chaves:

              - 'resenha_original': Vai conter a resenha original em inglês;
              - 'resenha_ptBR': Irá conter a resenha traduzida para o português;
              - 'categoria': Irá conter a categoria dentre as 5 definidas por você em que a resenha se encaixa'

              Exemplo:

              {{'resenha_original': 'I didn't like the color of the product',
              'resenha_ptBR': 'Eu não gostei da cor do produto',
              'categoria': 'design'}}

              Retorne APENAS o texto JSON. Não escreva nada mais além do texto JSON.

              Faça isto para todas as resenhas que eu te enviar abaixo:

              {resenhas_negativas_unidas} """
)

json_de_resenhas_classificadas = dicionario_de_resenhas_classificadas.text

print(json_de_resenhas_classificadas)

In [ ]:
import json

json_de_resenhas_classificadas_limpo = json_de_resenhas_classificadas.replace("```json", "").replace("```", "")

dicionario_de_resenhas_negativas_classificadas = json.loads(json_de_resenhas_classificadas_limpo)
dicionario_de_resenhas_negativas_classificadas

In [ ]:
len(dicionario_de_resenhas_negativas_classificadas)

In [ ]:
dicionario_de_resenhas_negativas_classificadas[22]