# 01. Fundamentos de Python

In [1]:
5

5

In [2]:
print(5)

5

In [3]:
print("Hello World !")

Hello World !

In [4]:
print('Hello World !')

Hello World !

In [5]:
print("Olá Mundo ! " + "5")

Olá Mundo ! 5

In [6]:
5 + 2

7

In [7]:
print(5 + 2)

7

In [8]:
produto1 = 5.00

In [9]:
produto1

5.0

In [10]:
print(produto1)

5.0

In [11]:
produto2 = 2000.00

In [12]:
print(produto2)

2000.0

In [13]:
produto3 = 1.00

In [14]:
print(f"Soma dos Produtos: {produto1 + produto2 + produto3}")

Soma dos Produtos: 2006.0

In [15]:
nome_do_produto1 = "Macarrão"

In [16]:
nome_do_produto2 = "Celular"

In [17]:
nome_do_produto3 = "Bala"

In [18]:
print(nome_do_produto1 + " " + nome_do_produto2 + " " + nome_do_produto3)

Macarrão Celular Bala

In [19]:
amigos = 5
aluguel = 1000.00
supermercado = 500.00
carro = 400.00

In [20]:
total = aluguel + supermercado + carro

In [21]:
print(total)

1900.0

In [22]:
aluguel = 900.0

In [23]:
print(total)

1900.0

In [24]:
total = aluguel + supermercado + carro

In [25]:
print(total)

1800.0

In [26]:
print(aluguel)

900.0

In [27]:
aluguel -= 100.0

In [28]:
print(aluguel)

800.0

In [29]:
aluguel -= 100.0

In [30]:
print(aluguel)

700.0

In [31]:
amigos = 6
aluguel = 1000.00
supermercado = 500.00
carro = 400.00

In [32]:
print(amigos)

6

In [33]:
total_de_carro = carro * 2

In [34]:
total = aluguel + supermercado + total_de_carro

In [35]:
print(total)

2300.0

In [36]:
total_por_pessoa = total / amigos

In [37]:
print(total_por_pessoa)

383.3333333333333

In [38]:
type(aluguel)

float

In [39]:
type(total_por_pessoa)

float

In [40]:
type(nome_do_produto1)

str

In [41]:
pedro_tem_carteira_motorista = True

mario_tem_carteira_motorista = False

In [42]:
type(pedro_tem_carteira_motorista)

bool

In [43]:
type(mario_tem_carteira_motorista)

bool

In [44]:
texto = "    Fabrício CARRaro  da alura   "
print(texto)

    Fabrício CARRaro  da alura

In [45]:
print(texto.lower())

    fabrício carraro  da alura

In [46]:
print(texto.upper())

    FABRÍCIO CARRARO  DA ALURA

In [47]:
print(texto.strip())

Fabrício CARRaro  da alura

In [48]:
print(texto.replace("  "," "))

  Fabrício CARRaro da alura

In [49]:
texto = texto.strip().upper().replace("  ", " ")

In [50]:
print(texto)

FABRÍCIO CARRARO DA ALURA

In [51]:
nome = input("Digite seu nome: ")

Digite seu nome: MacCloud

In [52]:
print(nome)

MacCloud

In [53]:
idade = input("Digite sua idade: ")

Digite sua idade: 508

In [54]:
print(idade)

508

In [55]:
type(nome)

str

In [56]:
type(idade)

str

In [57]:
idade = int(idade)

In [58]:
type(idade)

int

In [59]:
print(f"A pessoa se chama {nome} e tem {idade} anos de idade")

A pessoa se chama MacCloud e tem 508 anos de idade

In [60]:
idade = int(input("Digite sua idade: "))

Digite sua idade: 508

In [61]:
type(idade)

int

In [62]:
if idade >= 18:
    print(f"O {nome} pode entrar na festa porque ele é maior de idade")
    print(f"Ele tem {idade} anos de idade")
else:
    print(f"O {nome} NÃO PODE entrar na festa porque ele é MENOR de idade")
    print(f"Ele tem {idade} anos de idade")

O MacCloud pode entrar na festa porque ele é maior de idade
Ele tem 508 anos de idade

In [63]:
media = float(input("Digite sua media: "))

Digite sua media: 9.7

In [64]:
media = float(input("Digite sua media: "))

if media >= 7.0:
  print("Aprovado")
elif media >= 5.0 and media < 7.0:
  print("Recuperação")
else:
  print("Reprovado")

Digite sua media: 9.9
Aprovado

### **Rodando a IA no Google Colab (Gemini)**

In [65]:
import os

from google.colab import userdata

# userdata.get('Gemini_API_Key')

os.environ["GOOGLE_API_KEY"] = userdata.get('Gemini_API_Key')

In [66]:
from google import genai

client = genai.Client()

In [68]:
resposta = client.models.generate_content(model='gemini-2.5-flash', contents="What is Agentic AI ?")

In [109]:
print(resposta.text)

**Agentic AI** refers to an artificial intelligence system that can **autonomously perceive its environment, reason about its goals, plan a sequence of actions, execute those actions, and adapt based on feedback, all to achieve a specified objective.**

In simpler terms, instead of just responding to a single prompt (like a typical ChatGPT interaction), an Agentic AI system can:

1.  **Understand a High-Level Goal:** You give it a task like "research the best AI tools for content creation and summarize their pros and cons."
2.  **Break Down the Goal into Sub-Tasks:** It might decide it needs to:
    *   Search for "AI content creation tools."
    *   Filter the results for top-rated or well-known ones.
    *   Visit the websites or read reviews for each tool.
    *   Extract features, pricing, and user feedback.
    *   Compare them.
    *   Synthesize a summary.
3.  **Execute Actions in the Real World:** This is a crucial differentiator. It can:
    *   Use a web browser to search the internet.
    *   Call APIs (Application Programming Interfaces) to interact with other software (e.g., a calendar, a database, an email client).
    *   Write and execute code.
    *   Interact with various tools.
4.  **Monitor and Self-Correct:** If a search query doesn't yield good results, it can reformulate it. If a website gives an error, it can try another. If its summary isn't detailed enough, it can go back and gather more information. This involves an **iterative loop** of "plan -> act -> observe -> reflect -> replan."
5.  **Manage Memory and Context:** It remembers previous steps, observations, and decisions to maintain coherence throughout the task.

**Key Characteristics of Agentic AI:**

*   **Goal-Oriented:** Driven by a specific objective.
*   **Proactive, not just Reactive:** It initiates actions rather than just responding to prompts.
*   **Autonomous:** Can operate with minimal human intervention once given a goal.
*   **Tool-Using:** Leverages external resources and applications to extend its capabilities.
*   **Iterative & Adaptive:** Learns and adjusts its approach based on the outcomes of its actions.
*   **Planning & Reasoning:** Can strategize and infer logical steps to reach a goal.

**How it Differs from Traditional AI/LLMs:**

*   **Traditional LLMs (like standard ChatGPT):** Are primarily reactive. You ask a question, it gives an answer. It's a single "turn" of interaction. It doesn't inherently plan multi-step actions or interact with external tools beyond its training data.
*   **Agentic AI:** Uses an LLM as its "brain" for reasoning, planning, and interpreting, but it *surrounds* that LLM with modules for memory, tool execution, and feedback loops, enabling it to act like a smart, proactive assistant.

**Examples of Agentic AI in Action:**

*   **Automated Research Assistant:** You ask it to "write a report on the impact of climate change on coastal cities," and it will browse the web, synthesize information, and draft the report.
*   **Personal Assistant:** You tell it to "plan my weekend trip to Seattle," and it will check flights, hotels, local attractions, make recommendations, and potentially even book things (with your final approval).
*   **Software Development Assistant:** You ask it to "create a simple to-do list application," and it might write the code, test it, debug errors, and present a working application.
*   **Data Analysis Agent:** You provide it with a dataset and a question like "find the key trends in customer churn," and it will write and run scripts, generate visualizations, and summarize its findings.

Agentic AI represents a significant step towards more autonomous and capable AI systems that can handle complex, real-world tasks requiring multiple steps and interactions.

**Loops**

In [69]:
n = 1

while n <= 5:
  print("*")
  n += 1

*
*
*
*
*

In [70]:
chat = client.chats.create(model='gemini-2.5-flash')

In [71]:
resposta2 = chat.send_message("O que é a Inteligência Artificial ?")

In [72]:
#print(resposta2)
print(resposta2.text)

A **Inteligência Artificial (IA)** é um campo da ciência da computação dedicado a criar sistemas e máquinas capazes de simular a inteligência humana. O objetivo é desenvolver tecnologias que possam realizar tarefas que, normalmente, exigiriam inteligência humana, como aprender, raciocinar, resolver problemas, perceber, compreender a linguagem e tomar decisões.

### Componentes Chave da IA:

1.  **Aprendizado de Máquina (Machine Learning - ML):** É a subárea mais proeminente da IA hoje. Permite que sistemas aprendam a partir de dados, identifiquem padrões e tomem decisões com base nesses padrões, sem serem explicitamente programados para cada tarefa.
    *   **Aprendizado Supervisionado:** Treinar modelos com dados rotulados (ex: identificar imagens de gatos e cães).
    *   **Aprendizado Não Supervisionado:** Encontrar padrões em dados não rotulados (ex: agrupar clientes por comportamento de compra).
    *   **Aprendizado por Reforço:** Agentes aprendem a tomar decisões através de tentativa e erro, recebendo recompensas por ações desejadas (ex: jogos, carros autônomos).

2.  **Aprendizado Profundo (Deep Learning - DL):** Uma subárea do Machine Learning que utiliza redes neurais artificiais com múltiplas camadas (redes neurais profundas) para aprender representações complexas de dados. É extremamente eficaz em tarefas como reconhecimento de imagens, voz e processamento de linguagem natural.

3.  **Processamento de Linguagem Natural (NLP):** Permite que computadores compreendam, interpretem e gerem a linguagem humana de forma útil. Exemplos incluem assistentes de voz, tradutores automáticos e análise de sentimentos.

4.  **Visão Computacional (Computer Vision):** Capacita máquinas a "ver" e interpretar o mundo visual, processando imagens e vídeos para identificar objetos, pessoas, texto e cenas. É fundamental para carros autônomos e reconhecimento facial.

5.  **Sistemas Especialistas:** Programas que simulam o conhecimento e a capacidade de raciocínio de um especialista humano em um domínio específico para resolver problemas complexos.

### Tipos de IA:

*   **IA Fraca (Narrow AI ou Weak AI):** É a IA que existe atualmente. É projetada e treinada para uma tarefa específica (ex: reconhecimento facial, recomendação de produtos, jogar xadrez). Ela não possui consciência ou capacidade de generalizar o aprendizado para outras áreas.
*   **IA Forte (General AI ou Strong AI / Inteligência Artificial Geral - AGI):** É um conceito teórico de IA que teria a capacidade intelectual de um ser humano em todas as tarefas, incluindo raciocínio, resolução de problemas, aprendizado e compreensão da linguagem em qualquer contexto. Ainda está no campo da pesquisa e ficção científica.
*   **Superinteligência Artificial:** Uma IA hipotética que excede a inteligência humana em todos os aspectos.

### Exemplos do dia a dia:

*   **Assistentes Virtuais:** Siri, Alexa, Google Assistant.
*   **Sistemas de Recomendação:** Netflix, Amazon, Spotify.
*   **Carros Autônomos:** Tesla, Waymo.
*   **Filtros de Spam:** Identificam e bloqueiam e-mails indesejados.
*   **Detecção de Fraudes:** Em transações bancárias.
*   **Diagnóstico Médico:** Auxiliando na análise de exames e identificação de doenças.
*   **Tradutores Automáticos:** Google Translate.

Em suma, a IA busca criar sistemas que possam realizar tarefas de forma inteligente, aprendendo com dados e adaptando-se a novas situações, transformando a maneira como interagimos com a tecnologia e o mundo.

In [73]:
resposta3 = chat.send_message("Quando foi lançado o ChatGPT ?")

print(resposta3.text)

O **ChatGPT** foi lançado para o público em **30 de novembro de 2022**.

Foi um lançamento da OpenAI, e sua popularidade explodiu rapidamente devido à sua capacidade de gerar textos coerentes e contextualmente relevantes em uma ampla variedade de tópicos.

In [74]:
chat.get_history()

[UserContent(
   parts=[
     Part(
       text='O que é a Inteligência Artificial ?'
     ),
   ],
   role='user'
 ),
 Content(
   parts=[
     Part(
       text="""A **Inteligência Artificial (IA)** é um campo da ciência da computação dedicado a criar sistemas e máquinas capazes de simular a inteligência humana. O objetivo é desenvolver tecnologias que possam realizar tarefas que, normalmente, exigiriam inteligência humana, como aprender, raciocinar, resolver problemas, perceber, compreender a linguagem e tomar decisões.

 ### Componentes Chave da IA:

 1.  **Aprendizado de Máquina (Machine Learning - ML):** É a subárea mais proeminente da IA hoje. Permite que sistemas aprendam a partir de dados, identifiquem padrões e tomem decisões com base nesses padrões, sem serem explicitamente programados para cada tarefa.
     *   **Aprendizado Supervisionado:** Treinar modelos com dados rotulados (ex: identificar imagens de gatos e cães).
     *   **Aprendizado Não Supervisionado:** Encontrar padrões em dados não rotulados (ex: agrupar clientes por comportamento de compra).
     *   **Aprendizado por Reforço:** Agentes aprendem a tomar decisões através de tentativa e erro, recebendo recompensas por ações desejadas (ex: jogos, carros autônomos).

 2.  **Aprendizado Profundo (Deep Learning - DL):** Uma subárea do Machine Learning que utiliza redes neurais artificiais com múltiplas camadas (redes neurais profundas) para aprender representações complexas de dados. É extremamente eficaz em tarefas como reconhecimento de imagens, voz e processamento de linguagem natural.

 3.  **Processamento de Linguagem Natural (NLP):** Permite que computadores compreendam, interpretem e gerem a linguagem humana de forma útil. Exemplos incluem assistentes de voz, tradutores automáticos e análise de sentimentos.

 4.  **Visão Computacional (Computer Vision):** Capacita máquinas a "ver" e interpretar o mundo visual, processando imagens e vídeos para identificar objetos, pessoas, texto e cenas. É fundamental para carros autônomos e reconhecimento facial.

 5.  **Sistemas Especialistas:** Programas que simulam o conhecimento e a capacidade de raciocínio de um especialista humano em um domínio específico para resolver problemas complexos.

 ### Tipos de IA:

 *   **IA Fraca (Narrow AI ou Weak AI):** É a IA que existe atualmente. É projetada e treinada para uma tarefa específica (ex: reconhecimento facial, recomendação de produtos, jogar xadrez). Ela não possui consciência ou capacidade de generalizar o aprendizado para outras áreas.
 *   **IA Forte (General AI ou Strong AI / Inteligência Artificial Geral - AGI):** É um conceito teórico de IA que teria a capacidade intelectual de um ser humano em todas as tarefas, incluindo raciocínio, resolução de problemas, aprendizado e compreensão da linguagem em qualquer contexto. Ainda está no campo da pesquisa e ficção científica.
 *   **Superinteligência Artificial:** Uma IA hipotética que excede a inteligência humana em todos os aspectos.

 ### Exemplos do dia a dia:

 *   **Assistentes Virtuais:** Siri, Alexa, Google Assistant.
 *   **Sistemas de Recomendação:** Netflix, Amazon, Spotify.
 *   **Carros Autônomos:** Tesla, Waymo.
 *   **Filtros de Spam:** Identificam e bloqueiam e-mails indesejados.
 *   **Detecção de Fraudes:** Em transações bancárias.
 *   **Diagnóstico Médico:** Auxiliando na análise de exames e identificação de doenças.
 *   **Tradutores Automáticos:** Google Translate.

 Em suma, a IA busca criar sistemas que possam realizar tarefas de forma inteligente, aprendendo com dados e adaptando-se a novas situações, transformando a maneira como interagimos com a tecnologia e o mundo."""
     ),
   ],
   role='model'
 ),
 UserContent(
   parts=[
     Part(
       text='Quando foi lançado o ChatGPT ?'
     ),
   ],
   role='user'
 ),
 Content(
   parts=[
     Part(
       text="""O **ChatGPT** foi lançado para o público em **30 de novembro de 2022**.

 Foi um lançamento da OpenAI, e sua popularidade explodiu rapidamente devido à sua capacidade de gerar textos coerentes e contextualmente relevantes em uma ampla variedade de tópicos."""
     ),
   ],
   role='model'
 )]

In [75]:
prompt = input("Digite sua pergunta: ")

while prompt != "fim":
  resposta4 = chat.send_message(prompt)
  print(f"{resposta4.text} \n")
  prompt = input("Digite sua pergunta: ")

  print(resposta4.text)

Digite sua pergunta: O que é Deep Learning ?
**Deep Learning (Aprendizado Profundo)** é uma subárea do **Machine Learning (Aprendizado de Máquina)**, que por sua vez é uma subárea da **Inteligência Artificial (IA)**.

Ele é baseado em **redes neurais artificiais** que possuem **múltiplas camadas** (daí o termo "profundo"). A ideia central é que essas redes, inspiradas vagamente no funcionamento do cérebro humano, podem aprender representações complexas de dados.

### O que significa "profundo"?

O termo "profundo" refere-se ao número de camadas ocultas na rede neural. Enquanto redes neurais tradicionais tinham apenas uma ou poucas camadas ocultas, uma rede de Deep Learning pode ter dezenas, centenas ou até milhares de camadas.

### Como funciona?

Cada camada da rede neural de Deep Learning é responsável por aprender características (features) cada vez mais abstratas e complexas dos dados de entrada.

Vamos usar um exemplo de reconhecimento de imagem:

1.  **Camadas Iniciais:** Podem aprender a detectar características simples, como bordas, linhas e cores em uma imagem.
2.  **Camadas Intermediárias:** Podem combinar essas bordas e linhas para identificar formas mais complexas, como olhos, narizes, cantos de objetos.
3.  **Camadas Finais:** Podem montar essas formas para reconhecer objetos completos, como um rosto, um carro ou um gato.

A grande inovação do Deep Learning é que ele **aprende automaticamente essas características** a partir dos dados brutos, sem a necessidade de um engenheiro humano "dizer" ao sistema o que procurar (processo conhecido como "engenharia de características manual"). Isso é uma diferença fundamental em relação a muitos métodos de Machine Learning tradicionais.

### Componentes Chave:

*   **Redes Neurais Artificiais:** A arquitetura subjacente, composta por "neurônios" interconectados organizados em camadas.
*   **Múltiplas Camadas (Profundidade):** Permitem o aprendizado hierárquico de características.
*   **Grandes Volumes de Dados:** O Deep Learning se beneficia enormemente de grandes quantidades de dados para treinar seus modelos e atingir alta precisão.
*   **Hardware Potente (GPUs):** O treinamento de modelos de Deep Learning é computacionalmente intensivo e geralmente requer unidades de processamento gráfico (GPUs) para acelerar os cálculos.
*   **Algoritmos de Otimização:** Como o "backpropagation" (retropropagação), que permite que a rede ajuste os pesos de suas conexões com base nos erros que comete, aprendendo e melhorando ao longo do tempo.

### Aplicações do Deep Learning:

O Deep Learning revolucionou muitas áreas da IA e está por trás de algumas das tecnologias mais avançadas que usamos hoje:

*   **Visão Computacional:**
    *   Reconhecimento facial
    *   Detecção de objetos (em carros autônomos, por exemplo)
    *   Diagnóstico médico por imagem (identificação de tumores em radiografias)
*   **Processamento de Linguagem Natural (NLP):**
    *   Tradutores automáticos (como o Google Translate)
    *   Chatbots e assistentes virtuais (como o ChatGPT, que usa modelos de Deep Learning chamados Transformers)
    *   Análise de sentimentos
*   **Reconhecimento de Voz:**
    *   Assistentes de voz (Siri, Alexa, Google Assistant)
*   **Sistemas de Recomendação:**
    *   Filmes (Netflix), músicas (Spotify), produtos (Amazon)
*   **Carros Autônomos:**
    *   Processamento de dados de sensores e câmeras para navegação e tomada de decisões.

Em resumo, o Deep Learning é uma metodologia poderosa dentro da IA que utiliza redes neurais artificiais com muitas camadas para aprender automaticamente e de forma hierárquica representações complexas de dados, levando a avanços significativos em tarefas que antes eram consideradas exclusivas da inteligência humana.

Digite sua pergunta: fim
**Deep Learning (Aprendizado Profundo)** é uma subárea do **Machine Learning (Aprendizado de Máquina)**, que por sua vez é uma subárea da **Inteligência Artificial (IA)**.

Ele é baseado em **redes neurais artificiais** que possuem **múltiplas camadas** (daí o termo "profundo"). A ideia central é que essas redes, inspiradas vagamente no funcionamento do cérebro humano, podem aprender representações complexas de dados.

### O que significa "profundo"?

O termo "profundo" refere-se ao número de camadas ocultas na rede neural. Enquanto redes neurais tradicionais tinham apenas uma ou poucas camadas ocultas, uma rede de Deep Learning pode ter dezenas, centenas ou até milhares de camadas.

### Como funciona?

Cada camada da rede neural de Deep Learning é responsável por aprender características (features) cada vez mais abstratas e complexas dos dados de entrada.

Vamos usar um exemplo de reconhecimento de imagem:

1.  **Camadas Iniciais:** Podem aprender a detectar características simples, como bordas, linhas e cores em uma imagem.
2.  **Camadas Intermediárias:** Podem combinar essas bordas e linhas para identificar formas mais complexas, como olhos, narizes, cantos de objetos.
3.  **Camadas Finais:** Podem montar essas formas para reconhecer objetos completos, como um rosto, um carro ou um gato.

A grande inovação do Deep Learning é que ele **aprende automaticamente essas características** a partir dos dados brutos, sem a necessidade de um engenheiro humano "dizer" ao sistema o que procurar (processo conhecido como "engenharia de características manual"). Isso é uma diferença fundamental em relação a muitos métodos de Machine Learning tradicionais.

### Componentes Chave:

*   **Redes Neurais Artificiais:** A arquitetura subjacente, composta por "neurônios" interconectados organizados em camadas.
*   **Múltiplas Camadas (Profundidade):** Permitem o aprendizado hierárquico de características.
*   **Grandes Volumes de Dados:** O Deep Learning se beneficia enormemente de grandes quantidades de dados para treinar seus modelos e atingir alta precisão.
*   **Hardware Potente (GPUs):** O treinamento de modelos de Deep Learning é computacionalmente intensivo e geralmente requer unidades de processamento gráfico (GPUs) para acelerar os cálculos.
*   **Algoritmos de Otimização:** Como o "backpropagation" (retropropagação), que permite que a rede ajuste os pesos de suas conexões com base nos erros que comete, aprendendo e melhorando ao longo do tempo.

### Aplicações do Deep Learning:

O Deep Learning revolucionou muitas áreas da IA e está por trás de algumas das tecnologias mais avançadas que usamos hoje:

*   **Visão Computacional:**
    *   Reconhecimento facial
    *   Detecção de objetos (em carros autônomos, por exemplo)
    *   Diagnóstico médico por imagem (identificação de tumores em radiografias)
*   **Processamento de Linguagem Natural (NLP):**
    *   Tradutores automáticos (como o Google Translate)
    *   Chatbots e assistentes virtuais (como o ChatGPT, que usa modelos de Deep Learning chamados Transformers)
    *   Análise de sentimentos
*   **Reconhecimento de Voz:**
    *   Assistentes de voz (Siri, Alexa, Google Assistant)
*   **Sistemas de Recomendação:**
    *   Filmes (Netflix), músicas (Spotify), produtos (Amazon)
*   **Carros Autônomos:**
    *   Processamento de dados de sensores e câmeras para navegação e tomada de decisões.

Em resumo, o Deep Learning é uma metodologia poderosa dentro da IA que utiliza redes neurais artificiais com muitas camadas para aprender automaticamente e de forma hierárquica representações complexas de dados, levando a avanços significativos em tarefas que antes eram consideradas exclusivas da inteligência humana.

### Estruturas de Dados

In [76]:
lista_de_nomes = ["Maria Silva", "João Santos", "Ana Oliveira", "Pedro Costa", "juliana Pereira"]

In [77]:
print(lista_de_nomes[3])

Pedro Costa

In [78]:
lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]

In [79]:
print(lista_de_nomes[3])

Pedro Costa

In [80]:
for i in range(len(lista_de_medias)):   # Percorre a lista de médias e some 1 ao valor de cada média.

  lista_de_medias[i] = lista_de_medias[i] + 1.0

  if lista_de_medias[i] > 10.0:
    lista_de_medias[i] = 10.0

  print(lista_de_medias[i])

9.9
8.5
5.2
2.4
10.0

In [81]:
lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]

In [82]:
n = 0

while n < len(lista_de_medias):

  lista_de_medias[n] += 1.0

  if lista_de_medias[n] > 10.0:
    lista_de_medias[n] = 10.0

  print(lista_de_medias[n])

  n += 1

9.9
8.5
5.2
2.4
10.0

In [83]:
len(lista_de_medias)

5

In [84]:
lista_de_medias[len(lista_de_medias) - 1 ]

10.0

In [85]:
lista_de_medias[-1]

10.0

In [86]:
lista_de_nomes

['Maria Silva',
 'João Santos',
 'Ana Oliveira',
 'Pedro Costa',
 'juliana Pereira']

In [88]:
lista_de_nomes[1:]

['João Santos', 'Ana Oliveira', 'Pedro Costa', 'juliana Pereira']

In [89]:
lista_de_nomes[0:]

['Maria Silva',
 'João Santos',
 'Ana Oliveira',
 'Pedro Costa',
 'juliana Pereira']

In [90]:
lista_de_nomes[:]

['Maria Silva',
 'João Santos',
 'Ana Oliveira',
 'Pedro Costa',
 'juliana Pereira']

In [91]:
lista_de_nomes[1:4]

['João Santos', 'Ana Oliveira', 'Pedro Costa']

In [92]:
lista_de_nomes[:4]

['Maria Silva', 'João Santos', 'Ana Oliveira', 'Pedro Costa']

In [93]:
lista_de_nomes.append("Fabrício")

In [94]:
lista_de_nomes

['Maria Silva',
 'João Santos',
 'Ana Oliveira',
 'Pedro Costa',
 'juliana Pereira',
 'Fabrício']

In [95]:
lista_de_nomes.extend(["Joana da Silva", "Paulo Silveira"])

In [96]:
lista_de_nomes

['Maria Silva',
 'João Santos',
 'Ana Oliveira',
 'Pedro Costa',
 'juliana Pereira',
 'Fabrício',
 'Joana da Silva',
 'Paulo Silveira']

In [97]:
lista_de_nomes.append(["Marcio Costa","Natalia Pedreira"])

In [98]:
lista_de_nomes[8]

['Marcio Costa', 'Natalia Pedreira']

In [99]:
lista_de_nomes[8][0]

'Marcio Costa'

In [100]:
lista_de_nomes = ["Maria Silva", "João Santos", "Ana Oliveira", "Pedro Costa", "juliana Pereira"]

In [101]:
lista_de_nomes.extend(["Joana da Silva", "Paulo Silveira"])

In [102]:
lista_de_nomes

['Maria Silva',
 'João Santos',
 'Ana Oliveira',
 'Pedro Costa',
 'juliana Pereira',
 'Joana da Silva',
 'Paulo Silveira']

In [103]:
lista_de_nomes.remove("Paulo Silveira")

In [104]:
lista_de_nomes

['Maria Silva',
 'João Santos',
 'Ana Oliveira',
 'Pedro Costa',
 'juliana Pereira',
 'Joana da Silva']

In [105]:
lista_de_nomes.pop()

'Joana da Silva'

In [106]:
lista_de_nomes

['Maria Silva',
 'João Santos',
 'Ana Oliveira',
 'Pedro Costa',
 'juliana Pereira']

In [107]:
lista_de_nomes.pop(2)

'Ana Oliveira'

In [108]:
lista_de_nomes

['Maria Silva', 'João Santos', 'Pedro Costa', 'juliana Pereira']

# Dicionários
# "chave".valor

In [110]:
dict_de_nomes_e_medias = {
    "Maria Silva": 8.9,
    "João Santos": 7.5,
    "Ana Oliveira": 4.2,
    "Pedro Costa": 1.4,
    "juliana Pereira": 9.5
}

In [111]:
dict_de_nomes_e_medias

{'Maria Silva': 8.9,
 'João Santos': 7.5,
 'Ana Oliveira': 4.2,
 'Pedro Costa': 1.4,
 'juliana Pereira': 9.5}

In [112]:
dict_de_nomes_e_medias["Maria Silva"]

8.9

In [113]:
dict_de_nomes_e_medias.get("Maria Silva")

8.9

In [114]:
dict_de_nomes_e_medias

{'Maria Silva': 8.9,
 'João Santos': 7.5,
 'Ana Oliveira': 4.2,
 'Pedro Costa': 1.4,
 'juliana Pereira': 9.5}

In [115]:
dict_de_nomes_e_medias.pop("juliana Pereira")

9.5

In [116]:
dict_de_nomes_e_medias

{'Maria Silva': 8.9,
 'João Santos': 7.5,
 'Ana Oliveira': 4.2,
 'Pedro Costa': 1.4}

In [117]:
dict_de_nomes_e_medias.items()

dict_items([('Maria Silva', 8.9), ('João Santos', 7.5), ('Ana Oliveira', 4.2), ('Pedro Costa', 1.4)])

In [118]:
dict_de_nomes_e_medias.keys()

dict_keys(['Maria Silva', 'João Santos', 'Ana Oliveira', 'Pedro Costa'])

In [119]:
dict_de_nomes_e_medias.values()

dict_values([8.9, 7.5, 4.2, 1.4])

# Desafio: Usar dicionários de forma que as chaves sejam "nome" e "média" e os valores sejam os nomes e médias dos alunos

In [120]:
dict_desafio = [
    {"nome": "Maria Silva",  "media": 8.9},
    {"nome": "João Santos",  "media": 7.5},
    {"nome": "Ana Oliveira", "media": 4.2},
    {"nome": "Pedro Costa",  "media": 1.4},
]

In [121]:
dict_desafio

[{'nome': 'Maria Silva', 'media': 8.9},
 {'nome': 'João Santos', 'media': 7.5},
 {'nome': 'Ana Oliveira', 'media': 4.2},
 {'nome': 'Pedro Costa', 'media': 1.4}]

In [122]:
dict_desafio[0]

{'nome': 'Maria Silva', 'media': 8.9}

In [123]:
dict_desafio[0]["media"]

8.9

In [124]:
nomes = ['Maria', 'João', 'Ana', 'Pedro', 'Juliana']

print(nomes[-1])  # Exibe 'Juliana'
print(nomes[-2])  # Exibe 'Pedro'

Juliana
Pedro

In [125]:
# Exemplo de slicing com índice negativo

ultimos_tres = nomes[-3:]

print(ultimos_tres)  # Exibe ['Ana', 'Pedro', 'Juliana']

['Ana', 'Pedro', 'Juliana']

In [126]:
dict_desafio = [
    {"nome": "Maria Silva",  "media": 8.9},
    {"nome": "João Santos",  "media": 7.5},
    {"nome": "Ana Oliveira", "media": 4.2},
    {"nome": "Pedro Costa",  "media": 1.4},
]

In [127]:
n = 0
while n < len(dict_desafio):
    print (dict_desafio[n])
    n += 1

{'nome': 'Maria Silva', 'media': 8.9}
{'nome': 'João Santos', 'media': 7.5}
{'nome': 'Ana Oliveira', 'media': 4.2}
{'nome': 'Pedro Costa', 'media': 1.4}

In [128]:
for elemento in dict_desafio:
    print(elemento)

{'nome': 'Maria Silva', 'media': 8.9}
{'nome': 'João Santos', 'media': 7.5}
{'nome': 'Ana Oliveira', 'media': 4.2}
{'nome': 'Pedro Costa', 'media': 1.4}

In [129]:
for n in range(5):
    print(n)

0
1
2
3
4

In [130]:
for n in range(2, 7):
    print(n)

2
3
4
5
6

In [131]:
for n in range(2, 7, 2):
    print(n)

2
4
6

In [139]:
pessoa = {
    "nome": "Fabrício",
    "idade": 19,
    "altura": 1.87
}

print(pessoa)

{'nome': 'Fabrício', 'idade': 19, 'altura': 1.87}

In [140]:
for key in pessoa:
    print(key)

nome
idade
altura

In [141]:
pessoa.items()

dict_items([('nome', 'Fabrício'), ('idade', 19), ('altura', 1.87)])

In [142]:
for key,value in pessoa.items():
    print(f"A chave é {key} e o valor é {value}")

A chave é nome e o valor é Fabrício
A chave é idade e o valor é 19
A chave é altura e o valor é 1.87

In [143]:
for n in range(0,11):
    if n % 2 == 0 :
        print(n)

0
2
4
6
8
10

In [177]:
texto1 = "    Fabrício CARRaro  da alura   "
texto2 = "mArIA    aNA     sAntoS.  pereiRA"
texto3 = "  PeDRO.  alvaRes  cabrAl "
texto4 = "   anA   caroLINa.    FerreirA  "
texto5 = "  rObertO.   carlOS.     OliveiRa  "

In [170]:
texto1.split()

['Fabrício', 'CARRaro', 'da', 'alura']

In [171]:
len(texto1.split())

4

In [163]:
def escreve_texto_corretamente(texto):
    texto_novo = texto.strip().upper().replace("  "," ")
    #lista_de_palavras = texto_novo.split()
    #nome_final = " ".join(lista_de_palavras)
    #print(nome_final)
    print(texto_novo)

In [182]:
def escreve_texto_corretamente2(texto):
    texto_novo = texto.upper()
    lista_de_palavras = texto_novo.split()
    nome_final = " ".join(lista_de_palavras)
    print(nome_final)
    #print(texto_novo)

In [183]:
escreve_texto_corretamente2(texto1)

FABRÍCIO CARRARO DA ALURA

In [184]:
escreve_texto_corretamente2(texto2)

MARIA ANA SANTOS. PEREIRA

In [185]:
def escreve_texto_corretamente_alternativa(texto):
    nome_final = " ".join(texto.upper().split())
    return nome_final

In [186]:
escreve_texto_corretamente_alternativa(texto1)

'FABRÍCIO CARRARO DA ALURA'

In [187]:
salas_de_aula = ["sala 1", "sala 2", "sala 3"]

In [188]:
import random

def aloca_alunos_em_salas(nome_do_aluno, lista_de_salas):
    sala_do_aluno = random.choice(lista_de_salas)

    dict_aluno = {
        "nome": nome_do_aluno,
        "sala": sala_do_aluno
    }
    print(dict_aluno)

In [189]:
nome_processado = escreve_texto_corretamente_alternativa(texto1)

In [190]:
#aloca_alunos_em_salas(nome_processado, salas_de_aula)
aloca_alunos_em_salas(nome_processado, ["Classe 1", "Classe 2", "Classe 3"])

{'nome': 'FABRÍCIO CARRARO DA ALURA', 'sala': 'Classe 2'}

In [191]:
"""
Desafio:

1. Pedir para IA gerar em Python uma lista de 20 emails para você.
2. Criar uma função que vai receber uma lista de emails , percorrer esta lista de emails e para cada email da lista,
 ela irá chamar o gemini e pedir para ela resumir todos os emails em apenas 1 linha, definindo o que a pessoa queria no
  email.
"""

'\nDesafio:\n\n1. Pedir para IA gerar em Python uma lista de 20 emails para você.\n2. Criar uma função que vai receber uma lista de emails , percorrer esta lista de emails e para cada email da lista,\n ela irá chamar o gemini e pedir para ela resumir todos os emails em apenas 1 linha, definindo o que a pessoa queria no\n  email.\n'

In [193]:
emails_bodies = [
    "Olá! Esperamos que esteja bem. Gostaríamos de lembrá-lo(a) sobre a renovação do seu plano anual. Aproveite o desconto exclusivo até o final da semana!",
    "Prezada cliente, informamos que sua encomenda foi enviada e o código de rastreio já está disponível em sua conta. Agradecemos por comprar conosco!",
    "Caro aluno, as inscrições para o próximo módulo do curso de Programação Web estão abertas. Garanta sua vaga com 20% de desconto até sexta-feira.",
    "Bom dia! Temos o prazer de anunciar o lançamento da nova linha de produtos ecológicos. Sustentabilidade e qualidade em um só lugar!",
    "Olá! Notamos que você deixou alguns itens no carrinho. Finalize sua compra hoje e receba frete grátis em todo o Brasil.",
    "Prezado parceiro, estamos organizando um evento exclusivo de networking para profissionais da área. Sua presença será muito bem-vinda!",
    "Olá, tudo bem? Seu agendamento para a consulta médica foi confirmado para o dia 5 de novembro às 15h. Contamos com sua pontualidade!",
    "Caro usuário, detectamos uma tentativa de login em sua conta. Se não foi você, altere sua senha imediatamente por segurança.",
    "Olá! Aproveite nossa promoção relâmpago: até 50% de desconto em eletrônicos e acessórios. Somente hoje!",
    "Bom dia! Sua reserva no Hotel Paraíso está confirmada. Estamos ansiosos para recebê-lo e tornar sua estadia inesquecível.",
    "Prezada cliente, seu pagamento foi processado com sucesso. O comprovante segue em anexo. Obrigado pela preferência!",
    "Olá, participante! Agradecemos por se inscrever no Workshop de Inovação. Em breve você receberá o link para acessar o evento online.",
    "Boa tarde! Estamos contratando novos talentos para nossa equipe de marketing digital. Envie seu currículo até o dia 10/11.",
    "Olá! Seu pedido de suporte foi recebido. Nossa equipe entrará em contato em até 24 horas para auxiliá-lo.",
    "Prezado leitor, a nova edição da nossa revista já está disponível. Confira as matérias especiais sobre tendências do mercado.",
    "Olá! Parabéns! Você foi selecionado para o programa de fidelidade Gold. Aproveite benefícios exclusivos e descontos personalizados.",
    "Caro cliente, estamos atualizando nossa política de privacidade. Recomendamos que leia as novas condições em nosso site.",
    "Bom dia! Convidamos você para participar da nossa pesquisa de satisfação. Sua opinião é muito importante para nós.",
    "Olá! Chegou a hora de planejar suas próximas férias. Descubra pacotes incríveis com até 30% de desconto.",
    "Prezado(a), lembramos que o prazo para entrega do relatório trimestral é dia 31/10. Por favor, envie dentro do prazo para evitar penalidades."
]

In [194]:
def resumidor_de_emails(lista_de_emails):
    for numero, email in enumerate(lista_de_emails):
        resposta = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=f"""Vou te mandar o corpo de um e-mail. Quero que você o resuma em apenas uma linha,
                     passando o intuito daquele email. Segue o e-mail: {email}"""
            )
        print(f"E-mail: {numero + 1}: {resposta.text} ")
        print("-" * 50 )

In [196]:
resumidor_de_emails(emails_bodies)

E-mail: 1: Aqui está:

Lembrete para renovar seu plano anual e aproveitar um desconto exclusivo por tempo limitado.
--------------------------------------------------
E-mail: 2: Confirmação do envio da sua encomenda com código de rastreio disponível na sua conta.
--------------------------------------------------
E-mail: 3: **Inscreva-se no próximo módulo de Programação Web para garantir 20% de desconto até sexta-feira.**
--------------------------------------------------
E-mail: 4: O e-mail anuncia o lançamento de uma nova linha de produtos ecológicos focada em sustentabilidade e qualidade.
--------------------------------------------------

ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 37.611923723s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '37s'}]}}

In [ ]:
!pip install -q groq

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.8/135.8 kB 5.2 MB/s eta 0:00:00

In [ ]:
import os

from google.colab import userdata

In [ ]:
os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

In [ ]:
from groq import Groq

client_groq = Groq()

completion = client_groq.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
      {
        "role": "user",
        "content": "O que oferece mais vagas para contratação: PyTorch ou TensorFlow / Keras ?"
      }
    ],
    temperature=1,  # 0: O menos criativo possível,   2: O mais criativo possível.
    max_completion_tokens=8192,
    top_p=1,
    reasoning_effort="medium",
    stream=True,
    stop=None
)

for chunk in completion:
    print(chunk.choices[0].delta.content or "", end="")

## Resposta em português

### Qual framework gera mais vagas de emprego?
Em geral, **TensorFlow (incluindo Keras)** tem um número ligeiramente maior de anúncios de emprego do que PyTorch, mas a diferença não é gigantesca. A maioria das oportunidades de “data scientist”, “ML engineer” e “AI researcher” pede pelo menos conhecimento em *um* dos dois, e em muitos casos ambos.

| Fonte | Vagas com TensorFlow | Vagas com PyTorch | Observação |
|-------|---------------------|-------------------|------------|
| **LinkedIn (2024)** | ~3.700 | ~2.800 | TensorFlow aparece mais vezes, mas PyTorch está crescendo. |
| **Indeed (2024)** | ~4.200 | ~3.200 | Empresas de grande porte (Google, IBM, AWS) listam mais frequentemente TensorFlow. |
| **Glassdoor (2024)** | ~2.500 | ~2.000 | Vagas de estágio e de nível júnior tendem a citar mais PyTorch (Facebook, startups). |
| **Stack Overflow Jobs (2024)** | ~1.900 | ~1.600 | Stack Overflow reflete mais a comunidade de desenvolvedores. |

> **Resumo rápido:** TensorFlow/Keras é usado em cerca de 20‑30 % mais vagas que PyTorch em mercados globais, mas a diferença diminui à medida que PyTorch se consolida em produção e em startups de IA.

### Por que essa diferença acontece?

| Fator | TensorFlow | PyTorch |
|-------|------------|---------|
| **Histórico de adoção** | 2015 – Google, amplamente adotado em produção (Mobile, Cloud). | 2016 – Facebook, forte na comunidade de pesquisa. |
| **Ecossistema de produção** | TensorFlow Serving, TensorFlow Lite, TensorFlow.js – ferramentas maduras para deployment. | PyTorch Serve, TorchServe, ONNX – ainda em desenvolvimento, mas em rápido crescimento. |
| **Facilidade de prototipagem** | Keras (API de alto nível) torna prototipagem rápida, mas pode ser menos flexível que PyTorch. | Dinamismo do “define-by-run” facilita experimentos em pesquisa. |
| **Integração com infra‑estrutura** | Muito integrado ao Google Cloud (AI Platform, Vertex AI). | Muito usado em ambientes de HPC, mas também tem integração com AWS e Azure. |
| **Cultura de empresa** | Empresas de tecnologia gigantes (Google, Microsoft, Amazon) usam TensorFlow; startups de IA variam. | Facebook, OpenAI, DeepMind e muitas startups de IA preferem PyTorch. |

### Onde os empregos costumam ser listados?

| Tipo de vaga | Framework mais comum |
|--------------|---------------------|
| **ML Engineer (produção)** | TensorFlow (especialmente em empresas de grande porte) |
| **Research / Data Scientist** | PyTorch (principalmente em universidades e labs de pesquisa) |
| **Startups de IA** | Ambos – muitas vezes exigem “at least one”. |
| **Indústria de jogos** | PyTorch (Facebook AI e Unity) |
| **Mobile / IoT** | TensorFlow Lite, CoreML (Apple) |
| **Serviços de cloud** | TensorFlow (Google Cloud), PyTorch (AWS SageMaker, Azure ML) |

### O que considerar se você está entrando no mercado

1. **Aprenda ambos.** A maioria dos empregadores aceita um conhecimento sólido em um dos dois e valoriza a capacidade de aprender rapidamente o outro.
2. **Foque na “aplicação prática”.** Demonstrar projetos de produção (deploy, otimização, pipelines) pode ter mais peso que saber apenas “tecnicamente”.
3. **Acompanhe tendências.** Use o “Job Trends” do LinkedIn ou a “Job Market Insights” do Kaggle para ver quais palavras-chave estão em ascensão.
4. **Não se esqueça de Keras.** Como Keras agora é a API padrão de alto nível do TensorFlow, saber usá‑lo faz parte da stack do TensorFlow e é frequentemente solicitado em vagas “TensorFlow”.

### Conclusão

- **TensorFlow/Keras** tende a oferecer *um pouco mais* de vagas globais, principalmente em ambientes de produção e grandes empresas de cloud.
- **PyTorch** está ganhando espaço rapidamente, especialmente em pesquisa, academia e startups de IA, e sua demanda está quase se equiparando à do TensorFlow.
- **Dica prática:** se você está começando, aprenda TensorFlow (incluindo Keras) porque cobre mais vagas de início imediato; depois, expanda para PyTorch para se destacar em projetos de pesquisa e startups inovadoras.

Boa sorte na sua jornada no mercado de IA! 🚀

# Operador de Resto

In [ ]:
for n in range(11):
    if n % 2 == 0:
        print(n)  # Imprime números pares: 0, 2, 4, 6, 8, 10

0
2
4
6
8
10

In [ ]:
lista = ['a', 'b', 'c', 'd']

len(lista)

4

In [ ]:

for i in range(10):

    print(lista[i % len(lista)])  # Acessa sempre um índice válido na lista

a
b
c
d
a
b
c
d
a
b

# Leitura e Escrita de Arquivos

In [ ]:
from google import genai

client = genai.Client()

In [ ]:
def resumidor_de_emails(lista_de_emails):

    lista_de_resumos =[]

    for numero, email in enumerate(lista_de_emails):

        resposta = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=f"""Vou te mandar o corpo de um e-mail. Quero que você o resuma em apenas uma linha,
                     passando o intuito daquele email. Segue o e-mail: {email}"""
            )

        print(f"E-mail: {numero + 1}: {resposta.text} ")

        lista_de_resumos.append(f"E-mail: {numero + 1}: {resposta.text} ")

        print("-" * 50 )

    return lista_de_resumos

In [ ]:
lista_resumos = resumidor_de_emails(emails_bodies)

E-mail: 1: Lembrete para renovar seu plano anual e aproveitar um desconto exclusivo.
--------------------------------------------------
E-mail: 2: **Confirmação de envio da sua encomenda com código de rastreio.**
--------------------------------------------------
E-mail: 3: As inscrições para o próximo módulo de Programação Web estão abertas com 20% de desconto até sexta-feira.
--------------------------------------------------
E-mail: 4: Anúncio da nova linha de produtos ecológicos, focada em sustentabilidade e qualidade.
--------------------------------------------------
E-mail: 5: Incentivar a finalização da compra de itens no carrinho com a oferta de frete grátis.
--------------------------------------------------
E-mail: 6: Você está convidado para um evento exclusivo de networking.
--------------------------------------------------
E-mail: 7: **Confirmação da sua consulta médica para 5 de novembro às 15h, com lembrete de pontualidade.**
--------------------------------------------------
E-mail: 8: Alerta de segurança sobre tentativa de login, instruindo a alteração imediata da senha.
--------------------------------------------------
E-mail: 9: Anúncio de uma promoção relâmpago com até 50% de desconto em eletrônicos e acessórios, válida apenas hoje.
--------------------------------------------------
E-mail: 10: **Confirmação da sua reserva no Hotel Paraíso.**
--------------------------------------------------
E-mail: 11: Confirmação de pagamento bem-sucedido com comprovante em anexo.
--------------------------------------------------
E-mail: 12: **Confirmação da sua inscrição no Workshop de Inovação e aviso de que o link de acesso será enviado em breve.**
--------------------------------------------------
E-mail: 13: Claro! Aqui está:

**Contratação de talentos para marketing digital, com prazo de envio de currículo até 10/11.**
--------------------------------------------------
E-mail: 14: **Pedido de suporte recebido; aguarde contato em até 24h.**
--------------------------------------------------
E-mail: 15: A nova edição da revista, com foco em tendências do mercado, já está disponível.
--------------------------------------------------
E-mail: 16: **Você foi selecionado para o programa de fidelidade Gold, que oferece benefícios e descontos exclusivos.**
--------------------------------------------------
E-mail: 17: **Aviso de atualização da política de privacidade com recomendação para leitura das novas condições.**
--------------------------------------------------
E-mail: 18: Convite para pesquisa de satisfação, pois sua opinião é valiosa.
--------------------------------------------------
E-mail: 19: Aqui está:

**Descubra pacotes de férias com até 30% de desconto.**
--------------------------------------------------
E-mail: 20: O e-mail visa lembrar e incentivar a entrega do relatório trimestral até 31/10 para evitar penalidades.
--------------------------------------------------

In [ ]:
lista_resumos

['E-mail: 1: Lembrete para renovar seu plano anual e aproveitar um desconto exclusivo. ',
 'E-mail: 2: **Confirmação de envio da sua encomenda com código de rastreio.** ',
 'E-mail: 3: As inscrições para o próximo módulo de Programação Web estão abertas com 20% de desconto até sexta-feira. ',
 'E-mail: 4: Anúncio da nova linha de produtos ecológicos, focada em sustentabilidade e qualidade. ',
 'E-mail: 5: Incentivar a finalização da compra de itens no carrinho com a oferta de frete grátis. ',
 'E-mail: 6: Você está convidado para um evento exclusivo de networking. ',
 'E-mail: 7: **Confirmação da sua consulta médica para 5 de novembro às 15h, com lembrete de pontualidade.** ',
 'E-mail: 8: Alerta de segurança sobre tentativa de login, instruindo a alteração imediata da senha. ',
 'E-mail: 9: Anúncio de uma promoção relâmpago com até 50% de desconto em eletrônicos e acessórios, válida apenas hoje. ',
 'E-mail: 10: **Confirmação da sua reserva no Hotel Paraíso.** ',
 'E-mail: 11: Confirmação de pagamento bem-sucedido com comprovante em anexo. ',
 'E-mail: 12: **Confirmação da sua inscrição no Workshop de Inovação e aviso de que o link de acesso será enviado em breve.** ',
 'E-mail: 13: Claro! Aqui está:\n\n**Contratação de talentos para marketing digital, com prazo de envio de currículo até 10/11.** ',
 'E-mail: 14: **Pedido de suporte recebido; aguarde contato em até 24h.** ',
 'E-mail: 15: A nova edição da revista, com foco em tendências do mercado, já está disponível. ',
 'E-mail: 16: **Você foi selecionado para o programa de fidelidade Gold, que oferece benefícios e descontos exclusivos.** ',
 'E-mail: 17: **Aviso de atualização da política de privacidade com recomendação para leitura das novas condições.** ',
 'E-mail: 18: Convite para pesquisa de satisfação, pois sua opinião é valiosa. ',
 'E-mail: 19: Aqui está:\n\n**Descubra pacotes de férias com até 30% de desconto.** ',
 'E-mail: 20: O e-mail visa lembrar e incentivar a entrega do relatório trimestral até 31/10 para evitar penalidades. ']

In [ ]:
with open("lista-de-resumos.txt", "w", encoding="utf-8") as arquivo:

    for resumo in lista_resumos:

        arquivo.write(resumo + "\n")
        #arquivo.writelines(lista_resumos)

In [ ]:
print(lista_resumos)

['E-mail: 1: Lembrete para renovar seu plano anual e aproveitar um desconto exclusivo. ', 'E-mail: 2: **Confirmação de envio da sua encomenda com código de rastreio.** ', 'E-mail: 3: As inscrições para o próximo módulo de Programação Web estão abertas com 20% de desconto até sexta-feira. ', 'E-mail: 4: Anúncio da nova linha de produtos ecológicos, focada em sustentabilidade e qualidade. ', 'E-mail: 5: Incentivar a finalização da compra de itens no carrinho com a oferta de frete grátis. ', 'E-mail: 6: Você está convidado para um evento exclusivo de networking. ', 'E-mail: 7: **Confirmação da sua consulta médica para 5 de novembro às 15h, com lembrete de pontualidade.** ', 'E-mail: 8: Alerta de segurança sobre tentativa de login, instruindo a alteração imediata da senha. ', 'E-mail: 9: Anúncio de uma promoção relâmpago com até 50% de desconto em eletrônicos e acessórios, válida apenas hoje. ', 'E-mail: 10: **Confirmação da sua reserva no Hotel Paraíso.** ', 'E-mail: 11: Confirmação de pagamento bem-sucedido com comprovante em anexo. ', 'E-mail: 12: **Confirmação da sua inscrição no Workshop de Inovação e aviso de que o link de acesso será enviado em breve.** ', 'E-mail: 13: Claro! Aqui está:\n\n**Contratação de talentos para marketing digital, com prazo de envio de currículo até 10/11.** ', 'E-mail: 14: **Pedido de suporte recebido; aguarde contato em até 24h.** ', 'E-mail: 15: A nova edição da revista, com foco em tendências do mercado, já está disponível. ', 'E-mail: 16: **Você foi selecionado para o programa de fidelidade Gold, que oferece benefícios e descontos exclusivos.** ', 'E-mail: 17: **Aviso de atualização da política de privacidade com recomendação para leitura das novas condições.** ', 'E-mail: 18: Convite para pesquisa de satisfação, pois sua opinião é valiosa. ', 'E-mail: 19: Aqui está:\n\n**Descubra pacotes de férias com até 30% de desconto.** ', 'E-mail: 20: O e-mail visa lembrar e incentivar a entrega do relatório trimestral até 31/10 para evitar penalidades. ']

In [ ]:
with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:

    for linha in arquivo:
        print(linha)

E-mail: 1: Lembrete para renovar seu plano anual e aproveitar um desconto exclusivo.

E-mail: 2: **Confirmação de envio da sua encomenda com código de rastreio.**

E-mail: 3: As inscrições para o próximo módulo de Programação Web estão abertas com 20% de desconto até sexta-feira.

E-mail: 4: Anúncio da nova linha de produtos ecológicos, focada em sustentabilidade e qualidade.

E-mail: 5: Incentivar a finalização da compra de itens no carrinho com a oferta de frete grátis.

E-mail: 6: Você está convidado para um evento exclusivo de networking.

E-mail: 7: **Confirmação da sua consulta médica para 5 de novembro às 15h, com lembrete de pontualidade.**

E-mail: 8: Alerta de segurança sobre tentativa de login, instruindo a alteração imediata da senha.

E-mail: 9: Anúncio de uma promoção relâmpago com até 50% de desconto em eletrônicos e acessórios, válida apenas hoje.

E-mail: 10: **Confirmação da sua reserva no Hotel Paraíso.**

E-mail: 11: Confirmação de pagamento bem-sucedido com comprovante em anexo.

E-mail: 12: **Confirmação da sua inscrição no Workshop de Inovação e aviso de que o link de acesso será enviado em breve.**

E-mail: 13: Claro! Aqui está:



**Contratação de talentos para marketing digital, com prazo de envio de currículo até 10/11.**

E-mail: 14: **Pedido de suporte recebido; aguarde contato em até 24h.**

E-mail: 15: A nova edição da revista, com foco em tendências do mercado, já está disponível.

E-mail: 16: **Você foi selecionado para o programa de fidelidade Gold, que oferece benefícios e descontos exclusivos.**

E-mail: 17: **Aviso de atualização da política de privacidade com recomendação para leitura das novas condições.**

E-mail: 18: Convite para pesquisa de satisfação, pois sua opinião é valiosa.

E-mail: 19: Aqui está:



**Descubra pacotes de férias com até 30% de desconto.**

E-mail: 20: O e-mail visa lembrar e incentivar a entrega do relatório trimestral até 31/10 para evitar penalidades.

In [ ]:
nova_lista_de_leitura = []

with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:

    for linha in arquivo:
        nova_lista_de_leitura.append(linha.strip())

In [ ]:
nova_lista_de_leitura

['E-mail: 1: Lembrete para renovar seu plano anual e aproveitar um desconto exclusivo.',
 'E-mail: 2: **Confirmação de envio da sua encomenda com código de rastreio.**',
 'E-mail: 3: As inscrições para o próximo módulo de Programação Web estão abertas com 20% de desconto até sexta-feira.',
 'E-mail: 4: Anúncio da nova linha de produtos ecológicos, focada em sustentabilidade e qualidade.',
 'E-mail: 5: Incentivar a finalização da compra de itens no carrinho com a oferta de frete grátis.',
 'E-mail: 6: Você está convidado para um evento exclusivo de networking.',
 'E-mail: 7: **Confirmação da sua consulta médica para 5 de novembro às 15h, com lembrete de pontualidade.**',
 'E-mail: 8: Alerta de segurança sobre tentativa de login, instruindo a alteração imediata da senha.',
 'E-mail: 9: Anúncio de uma promoção relâmpago com até 50% de desconto em eletrônicos e acessórios, válida apenas hoje.',
 'E-mail: 10: **Confirmação da sua reserva no Hotel Paraíso.**',
 'E-mail: 11: Confirmação de pagamento bem-sucedido com comprovante em anexo.',
 'E-mail: 12: **Confirmação da sua inscrição no Workshop de Inovação e aviso de que o link de acesso será enviado em breve.**',
 'E-mail: 13: Claro! Aqui está:',
 '',
 '**Contratação de talentos para marketing digital, com prazo de envio de currículo até 10/11.**',
 'E-mail: 14: **Pedido de suporte recebido; aguarde contato em até 24h.**',
 'E-mail: 15: A nova edição da revista, com foco em tendências do mercado, já está disponível.',
 'E-mail: 16: **Você foi selecionado para o programa de fidelidade Gold, que oferece benefícios e descontos exclusivos.**',
 'E-mail: 17: **Aviso de atualização da política de privacidade com recomendação para leitura das novas condições.**',
 'E-mail: 18: Convite para pesquisa de satisfação, pois sua opinião é valiosa.',
 'E-mail: 19: Aqui está:',
 '',
 '**Descubra pacotes de férias com até 30% de desconto.**',
 'E-mail: 20: O e-mail visa lembrar e incentivar a entrega do relatório trimestral até 31/10 para evitar penalidades.']

In [ ]:
conteudo = ""

with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:

    conteudo = arquivo.read()

In [ ]:
conteudo

'E-mail: 1: Lembrete para renovar seu plano anual e aproveitar um desconto exclusivo. \nE-mail: 2: **Confirmação de envio da sua encomenda com código de rastreio.** \nE-mail: 3: As inscrições para o próximo módulo de Programação Web estão abertas com 20% de desconto até sexta-feira. \nE-mail: 4: Anúncio da nova linha de produtos ecológicos, focada em sustentabilidade e qualidade. \nE-mail: 5: Incentivar a finalização da compra de itens no carrinho com a oferta de frete grátis. \nE-mail: 6: Você está convidado para um evento exclusivo de networking. \nE-mail: 7: **Confirmação da sua consulta médica para 5 de novembro às 15h, com lembrete de pontualidade.** \nE-mail: 8: Alerta de segurança sobre tentativa de login, instruindo a alteração imediata da senha. \nE-mail: 9: Anúncio de uma promoção relâmpago com até 50% de desconto em eletrônicos e acessórios, válida apenas hoje. \nE-mail: 10: **Confirmação da sua reserva no Hotel Paraíso.** \nE-mail: 11: Confirmação de pagamento bem-sucedido com comprovante em anexo. \nE-mail: 12: **Confirmação da sua inscrição no Workshop de Inovação e aviso de que o link de acesso será enviado em breve.** \nE-mail: 13: Claro! Aqui está:\n\n**Contratação de talentos para marketing digital, com prazo de envio de currículo até 10/11.** \nE-mail: 14: **Pedido de suporte recebido; aguarde contato em até 24h.** \nE-mail: 15: A nova edição da revista, com foco em tendências do mercado, já está disponível. \nE-mail: 16: **Você foi selecionado para o programa de fidelidade Gold, que oferece benefícios e descontos exclusivos.** \nE-mail: 17: **Aviso de atualização da política de privacidade com recomendação para leitura das novas condições.** \nE-mail: 18: Convite para pesquisa de satisfação, pois sua opinião é valiosa. \nE-mail: 19: Aqui está:\n\n**Descubra pacotes de férias com até 30% de desconto.** \nE-mail: 20: O e-mail visa lembrar e incentivar a entrega do relatório trimestral até 31/10 para evitar penalidades. \n'

In [ ]:
nova_lista_de_leitura_2 = []

with open("lista-de-resumos.txt", "r", encoding="utf-8") as arquivo:

    nova_lista_de_leitura_2 = arquivo.readlines()

In [ ]:
nova_lista_de_leitura_2

['E-mail: 1: Lembrete para renovar seu plano anual e aproveitar um desconto exclusivo. \n',
 'E-mail: 2: **Confirmação de envio da sua encomenda com código de rastreio.** \n',
 'E-mail: 3: As inscrições para o próximo módulo de Programação Web estão abertas com 20% de desconto até sexta-feira. \n',
 'E-mail: 4: Anúncio da nova linha de produtos ecológicos, focada em sustentabilidade e qualidade. \n',
 'E-mail: 5: Incentivar a finalização da compra de itens no carrinho com a oferta de frete grátis. \n',
 'E-mail: 6: Você está convidado para um evento exclusivo de networking. \n',
 'E-mail: 7: **Confirmação da sua consulta médica para 5 de novembro às 15h, com lembrete de pontualidade.** \n',
 'E-mail: 8: Alerta de segurança sobre tentativa de login, instruindo a alteração imediata da senha. \n',
 'E-mail: 9: Anúncio de uma promoção relâmpago com até 50% de desconto em eletrônicos e acessórios, válida apenas hoje. \n',
 'E-mail: 10: **Confirmação da sua reserva no Hotel Paraíso.** \n',
 'E-mail: 11: Confirmação de pagamento bem-sucedido com comprovante em anexo. \n',
 'E-mail: 12: **Confirmação da sua inscrição no Workshop de Inovação e aviso de que o link de acesso será enviado em breve.** \n',
 'E-mail: 13: Claro! Aqui está:\n',
 '\n',
 '**Contratação de talentos para marketing digital, com prazo de envio de currículo até 10/11.** \n',
 'E-mail: 14: **Pedido de suporte recebido; aguarde contato em até 24h.** \n',
 'E-mail: 15: A nova edição da revista, com foco em tendências do mercado, já está disponível. \n',
 'E-mail: 16: **Você foi selecionado para o programa de fidelidade Gold, que oferece benefícios e descontos exclusivos.** \n',
 'E-mail: 17: **Aviso de atualização da política de privacidade com recomendação para leitura das novas condições.** \n',
 'E-mail: 18: Convite para pesquisa de satisfação, pois sua opinião é valiosa. \n',
 'E-mail: 19: Aqui está:\n',
 '\n',
 '**Descubra pacotes de férias com até 30% de desconto.** \n',
 'E-mail: 20: O e-mail visa lembrar e incentivar a entrega do relatório trimestral até 31/10 para evitar penalidades. \n']

## Manipulando Dados com Pandas

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/meu_csv.csv")

In [ ]:
df

       nome  media
0       Ana    7.5
1    Carlos    8.2
2   Beatriz    9.1
3     Diogo    6.8
4   Eduarda    5.9
5  Fernanda    8.5
6   Gustavo    7.3
7    Helena    9.5
8      Igor    6.1
9   Juliana    8.9

In [ ]:
df.head()

      nome  media
0      Ana    7.5
1   Carlos    8.2
2  Beatriz    9.1
3    Diogo    6.8
4  Eduarda    5.9

In [ ]:
df.head(7)

       nome  media
0       Ana    7.5
1    Carlos    8.2
2   Beatriz    9.1
3     Diogo    6.8
4   Eduarda    5.9
5  Fernanda    8.5
6   Gustavo    7.3

In [ ]:
df.tail()

       nome  media
5  Fernanda    8.5
6   Gustavo    7.3
7    Helena    9.5
8      Igor    6.1
9   Juliana    8.9

Desafio:
1. Criar um arquivo .txt a partir de uma lista de perguntas vindas de uma lista em Python.
2. Ler as perguntas desse arquivo .txt e salvar em uma lista Python.
3. Obter as respostas de um LLM para cada uma.
4. SAlvar os resultados em um novo arquivo .csv
5. Ler o arquivo .csv usando Pandas.

In [ ]:
# Step 1:
lista_10_perguntas = [
    "Qual é a lista de todos os filmes e seriados do personagem Batman ?",
    "Quantos bairros existem na cidade de Campinas em São Paulo ?",
    "Qual o tamnho da população de Campinas - SP ? ",
    "Quantos Shoppings Centers existem em Campinas - SP e quais são eles ?",
    "Quantas empresas de tecnologia existem em Campinas - SP e quais são elas ?",
    "Quais países no mundo estão atualmente, contratando mais profissionais em funções relacionadas a Inteligência Artificial ?",
    "Qual é a lista de todos os filmes e seriados do personagem Superman ?",
    "Quantos bairros existem na cidade de São Paulo em São Paulo ?",
    "Qual o tamnho da população de São Paulo - SP ? ",
    "Quantos Shoppings Centers existem em São Paulo - SP e quais são eles ?"
    ]

with open("perguntas.txt", "w", encoding="utf-8") as arquivo2:
    for pergunta in lista_10_perguntas:
        arquivo2.write(pergunta + "\n")

In [ ]:
# Step 2:

lista_desafio = []

with open("perguntas.txt", "r", encoding="utf-8") as arquivo3:

    for linha in arquivo3:

        lista_desafio.append(linha.strip())

print(lista_desafio)

['Qual é a lista de todos os filmes e seriados do personagem Batman ?', 'Quantos bairros existem na cidade de Campinas em São Paulo ?', 'Qual o tamnho da população de Campinas - SP ?', 'Quantos Shoppings Centers existem em Campinas - SP e quais são eles ?', 'Quantas empresas de tecnologia existem em Campinas - SP e quais são elas ?', 'Quais países no mundo estão atualmente, contratando mais profissionais em funções relacionadas a Inteligência Artificial ?', 'Qual é a lista de todos os filmes e seriados do personagem Superman ?', 'Quantos bairros existem na cidade de São Paulo em São Paulo ?', 'Qual o tamnho da população de São Paulo - SP ?', 'Quantos Shoppings Centers existem em São Paulo - SP e quais são eles ?']

In [ ]:

import os

from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('Gemini_API_Key')

In [ ]:
from google import genai

client = genai.Client()

In [ ]:

# Step 3:

lista_dicionario_respostas = []

for pergunta in lista_desafio:

    resposta = client.models.generate_content(
        model='gemini-2.5-flash',
        contents= f"Gere uma resposta muito sucinta para a pergunta: {pergunta}"
    )


    dicionario_respostas = {
        "pergunta": pergunta,
        "resposta": resposta.text
    }


    lista_dicionario_respostas.append(
        {
        "pergunta": pergunta,
        "resposta": resposta.text
        }
    )

In [ ]:
lista_dicionario_respostas

[{'pergunta': 'Qual é a lista de todos os filmes e seriados do personagem Batman ?',
  'resposta': 'É impossível listar *todos* de forma sucinta.\n\nO universo Batman tem centenas de produções, incluindo filmes live-action, animações (filmes e séries) e séries de TV, em constante expansão. Uma lista completa seria extensíssima.'},
 {'pergunta': 'Quantos bairros existem na cidade de Campinas em São Paulo ?',
  'resposta': 'Entre 150 e 160 bairros, aproximadamente.'},
 {'pergunta': 'Qual o tamnho da população de Campinas - SP ?',
  'resposta': 'Cerca de 1.1 milhão de habitantes (Censo 2022).'},
 {'pergunta': 'Quantos Shoppings Centers existem em Campinas - SP e quais são eles ?',
  'resposta': 'Existem 6: Parque Dom Pedro, Iguatemi, Galleria, Campinas Shopping, Bandeiras e Spazio Ouro Verde.'},
 {'pergunta': 'Quantas empresas de tecnologia existem em Campinas - SP e quais são elas ?',
  'resposta': 'Não há um número exato ou uma lista completa e oficial. Campinas abriga **centenas** de empresas de tecnologia, desde startups a grandes corporações e centros de P&D, como **CI&T, CPqD, Eldorado, HP (com presença), Samsung (P&D)**, entre muitas outras.'},
 {'pergunta': 'Quais países no mundo estão atualmente, contratando mais profissionais em funções relacionadas a Inteligência Artificial ?',
  'resposta': '**Estados Unidos e China.**\n\nCom forte demanda também no Reino Unido, Alemanha e Canadá.'},
 {'pergunta': 'Qual é a lista de todos os filmes e seriados do personagem Superman ?',
  'resposta': 'É **impossível listar *todos*** de forma sucinta.\n\nA quantidade de filmes, séries e animações do Superman é **muito extensa**, abrangendo décadas de produções.\n\nPara uma lista exaustiva, consulte bases de dados especializadas (IMDb, Wikipedia, etc.).'},
 {'pergunta': 'Quantos bairros existem na cidade de São Paulo em São Paulo ?',
  'resposta': '96 bairros (distritos).'},
 {'pergunta': 'Qual o tamnho da população de São Paulo - SP ?',
  'resposta': 'Aproximadamente 11,5 milhões (estimativa 2023).'},
 {'pergunta': 'Quantos Shoppings Centers existem em São Paulo - SP e quais são eles ?',
  'resposta': 'Existem **dezenas** de shoppings em São Paulo. Uma lista completa seria **muito extensa**.'}]

In [ ]:
# Step 4:

with open ("respostas1.csv", "w", encoding="utf-8") as arquivo4:

    arquivo4.write("pergunta,resposta\n")

    for pergunta_dict in lista_dicionario_respostas:
        # Remove internal newlines and enclose response in quotes
        resposta_formatada = pergunta_dict["resposta"].replace('\n', ' ').replace("\"", "\"\"")
        arquivo4.write(f'"{pergunta_dict["pergunta"]}","{resposta_formatada}"\n')

In [ ]:
# Step 4: (Usando PANDAS)

df_perguntas_e_respostas = pd.DataFrame(lista_dicionario_respostas)

In [ ]:
df_perguntas_e_respostas

,pergunta,resposta
0,Qual é a lista de todos os filmes e seriados d...,É impossível listar *todos* de forma sucinta.\...
1,Quantos bairros existem na cidade de Campinas ...,"Entre 150 e 160 bairros, aproximadamente."
2,Qual o tamnho da população de Campinas - SP ?,Cerca de 1.1 milhão de habitantes (Censo 2022).
3,Quantos Shoppings Centers existem em Campinas ...,"Existem 6: Parque Dom Pedro, Iguatemi, Galleri..."
4,Quantas empresas de tecnologia existem em Camp...,Não há um número exato ou uma lista completa e...
5,"Quais países no mundo estão atualmente, contra...",**Estados Unidos e China.**\n\nCom forte deman...
6,Qual é a lista de todos os filmes e seriados d...,É **impossível listar *todos*** de forma sucin...
7,Quantos bairros existem na cidade de São Paulo...,96 bairros (distritos).
8,Qual o tamnho da população de São Paulo - SP ?,"Aproximadamente 11,5 milhões (estimativa 2023)."
9,Quantos Shoppings Centers existem em São Paulo...,Existem **dezenas** de shoppings em São Paulo....

In [ ]:
df_perguntas_e_respostas.to_csv(
    "respostas2.csv",
    index=False,
    encoding="utf-8"
)

In [ ]:
df_perguntas_e_respostas

,pergunta,resposta
0,Qual é a lista de todos os filmes e seriados d...,É impossível listar *todos* de forma sucinta.\...
1,Quantos bairros existem na cidade de Campinas ...,"Entre 150 e 160 bairros, aproximadamente."
2,Qual o tamnho da população de Campinas - SP ?,Cerca de 1.1 milhão de habitantes (Censo 2022).
3,Quantos Shoppings Centers existem em Campinas ...,"Existem 6: Parque Dom Pedro, Iguatemi, Galleri..."
4,Quantas empresas de tecnologia existem em Camp...,Não há um número exato ou uma lista completa e...
5,"Quais países no mundo estão atualmente, contra...",**Estados Unidos e China.**\n\nCom forte deman...
6,Qual é a lista de todos os filmes e seriados d...,É **impossível listar *todos*** de forma sucin...
7,Quantos bairros existem na cidade de São Paulo...,96 bairros (distritos).
8,Qual o tamnho da população de São Paulo - SP ?,"Aproximadamente 11,5 milhões (estimativa 2023)."
9,Quantos Shoppings Centers existem em São Paulo...,Existem **dezenas** de shoppings em São Paulo....

In [ ]:
# Step 5:

novo_df = pd.read_csv("respostas2.csv")

In [ ]:
novo_df

,pergunta,resposta
0,Qual é a lista de todos os filmes e seriados d...,É impossível listar *todos* de forma sucinta.\...
1,Quantos bairros existem na cidade de Campinas ...,"Entre 150 e 160 bairros, aproximadamente."
2,Qual o tamnho da população de Campinas - SP ?,Cerca de 1.1 milhão de habitantes (Censo 2022).
3,Quantos Shoppings Centers existem em Campinas ...,"Existem 6: Parque Dom Pedro, Iguatemi, Galleri..."
4,Quantas empresas de tecnologia existem em Camp...,Não há um número exato ou uma lista completa e...
5,"Quais países no mundo estão atualmente, contra...",**Estados Unidos e China.**\n\nCom forte deman...
6,Qual é a lista de todos os filmes e seriados d...,É **impossível listar *todos*** de forma sucin...
7,Quantos bairros existem na cidade de São Paulo...,96 bairros (distritos).
8,Qual o tamnho da população de São Paulo - SP ?,"Aproximadamente 11,5 milhões (estimativa 2023)."
9,Quantos Shoppings Centers existem em São Paulo...,Existem **dezenas** de shoppings em São Paulo....

In [ ]:
import pandas as pd
import numpy as np

# Generating 50 rows of data
num_rows = 50

data = {
    'Nome do produto': [f'Produto_{i+1}' for i in range(num_rows)],
    'Categoria do produto': np.random.choice(['Eletrônicos', 'Acessórios', 'Informática', 'Periféricos', 'Componentes'], size=num_rows).tolist(),
    'Preço do produto': np.random.uniform(10.00, 2000.00, size=num_rows).round(2).tolist(),
    'Quantidade vendida': np.random.randint(1, 200, size=num_rows).tolist(),
    'Avaliação do produto': np.random.uniform(1.0, 5.0, size=num_rows).round(1).tolist()
}

df_produtos = pd.DataFrame(data)

display(df_produtos)

,Nome do produto,Categoria do produto,Preço do produto,Quantidade vendida,Avaliação do produto
0,Produto_1,Componentes,857.64,138,2.9
1,Produto_2,Acessórios,1503.65,58,1.8
2,Produto_3,Acessórios,404.40,195,1.8
3,Produto_4,Componentes,1105.61,177,3.4
4,Produto_5,Acessórios,952.10,87,4.8
5,Produto_6,Acessórios,36.76,10,2.9
6,Produto_7,Periféricos,1040.82,79,2.7
7,Produto_8,Periféricos,800.41,60,4.6
8,Produto_9,Componentes,1316.04,143,3.8
9,Produto_10,Componentes,720.04,20,4.0
10,Produto_11,Informática,1351.14,2,3.0
11,Produto_12,Acessórios,374.64,42,2.0
12,Produto_13,Acessórios,1917.02,194,2.2
13,Produto_14,Informática,1435.93,114,4.1
14,Produto_15,Acessórios,1938.07,22,4.9
15,Produto_16,Componentes,1218.39,5,3.1
16,Produto_17,Informática,768.95,148,1.3
17,Produto_18,Informática,383.95,115,3.0
18,Produto_19,Acessórios,721.19,176,1.1
19,Produto_20,Informática,508.93,116,2.0
20,Produto_21,Acessórios,1066.93,171,3.0
21,Produto_22,Componentes,930.38,173,3.9
22,Produto_23,Componentes,1744.26,54,4.7
23,Produto_24,Componentes,954.57,183,4.5
24,Produto_25,Informática,990.46,122,3.7
25,Produto_26,Periféricos,982.93,127,2.4
26,Produto_27,Eletrônicos,512.88,62,2.7
27,Produto_28,Informática,1751.42,66,2.1
28,Produto_29,Componentes,952.24,189,4.3
29,Produto_30,Informática,442.31,52,1.7
30,Produto_31,Componentes,824.67,7,4.1
31,Produto_32,Eletrônicos,1185.93,155,4.4
32,Produto_33,Componentes,352.62,171,2.9
33,Produto_34,Componentes,358.93,113,1.7
34,Produto_35,Componentes,245.67,187,3.0
35,Produto_36,Eletrônicos,1550.08,159,2.4
36,Produto_37,Periféricos,1645.40,37,2.3
37,Produto_38,Periféricos,1081.01,173,4.0
38,Produto_39,Eletrônicos,212.39,112,3.9
39,Produto_40,Informática,694.05,20,2.6
40,Produto_41,Acessórios,1943.37,122,1.6
41,Produto_42,Componentes,1555.46,95,2.1
42,Produto_43,Periféricos,66.94,190,4.3
43,Produto_44,Componentes,719.67,46,2.6
44,Produto_45,Acessórios,786.37,156,3.1
45,Produto_46,Eletrônicos,54.37,121,3.5
46,Produto_47,Acessórios,1811.84,44,1.5
47,Produto_48,Eletrônicos,811.68,74,2.3
48,Produto_49,Componentes,1886.37,143,1.1
49,Produto_50,Acessórios,1560.70,44,1.1

In [ ]:
df_produtos["Categoria do produto"]

0     Componentes
1      Acessórios
2      Acessórios
3     Componentes
4      Acessórios
5      Acessórios
6     Periféricos
7     Periféricos
8     Componentes
9     Componentes
10    Informática
11     Acessórios
12     Acessórios
13    Informática
14     Acessórios
15    Componentes
16    Informática
17    Informática
18     Acessórios
19    Informática
20     Acessórios
21    Componentes
22    Componentes
23    Componentes
24    Informática
25    Periféricos
26    Eletrônicos
27    Informática
28    Componentes
29    Informática
30    Componentes
31    Eletrônicos
32    Componentes
33    Componentes
34    Componentes
35    Eletrônicos
36    Periféricos
37    Periféricos
38    Eletrônicos
39    Informática
40     Acessórios
41    Componentes
42    Periféricos
43    Componentes
44     Acessórios
45    Eletrônicos
46     Acessórios
47    Eletrônicos
48    Componentes
49     Acessórios
Name: Categoria do produto, dtype: object

In [ ]:
df_produtos["Categoria do produto"].unique()

array(['Componentes', 'Acessórios', 'Periféricos', 'Informática',
       'Eletrônicos'], dtype=object)

In [ ]:
set(df_produtos["Categoria do produto"])

{'Acessórios', 'Componentes', 'Eletrônicos', 'Informática', 'Periféricos'}

## Filtrando elementos de um Dataframe Pandas

In [ ]:
df_produtos["Categoria do produto"] == "Informática"

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13     True
14    False
15    False
16     True
17     True
18    False
19     True
20    False
21    False
22    False
23    False
24     True
25    False
26    False
27     True
28    False
29     True
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39     True
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: Categoria do produto, dtype: bool

In [ ]:
df_produtos[df_produtos["Categoria do produto"] == "Informática"]

,Nome do produto,Categoria do produto,Preço do produto,Quantidade vendida,Avaliação do produto
10,Produto_11,Informática,1351.14,2,3.0
13,Produto_14,Informática,1435.93,114,4.1
16,Produto_17,Informática,768.95,148,1.3
17,Produto_18,Informática,383.95,115,3.0
19,Produto_20,Informática,508.93,116,2.0
24,Produto_25,Informática,990.46,122,3.7
27,Produto_28,Informática,1751.42,66,2.1
29,Produto_30,Informática,442.31,52,1.7
39,Produto_40,Informática,694.05,20,2.6

In [ ]:
df_produtos[df_produtos["Avaliação do produto"] < 2.0 ]

,Nome do produto,Categoria do produto,Preço do produto,Quantidade vendida,Avaliação do produto
1,Produto_2,Acessórios,1503.65,58,1.8
2,Produto_3,Acessórios,404.40,195,1.8
16,Produto_17,Informática,768.95,148,1.3
18,Produto_19,Acessórios,721.19,176,1.1
29,Produto_30,Informática,442.31,52,1.7
33,Produto_34,Componentes,358.93,113,1.7
40,Produto_41,Acessórios,1943.37,122,1.6
46,Produto_47,Acessórios,1811.84,44,1.5
48,Produto_49,Componentes,1886.37,143,1.1
49,Produto_50,Acessórios,1560.70,44,1.1

In [ ]:
df_produtos.shape

(50, 5)

In [ ]:
filtro_menor_2 = df_produtos["Avaliação do produto"] < 2.0

filtro_categoria_produto = df_produtos["Categoria do produto"] == "Informática"

In [ ]:
filtro_menor_2

0     False
1      True
2      True
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16     True
17    False
18     True
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29     True
30    False
31    False
32    False
33     True
34    False
35    False
36    False
37    False
38    False
39    False
40     True
41    False
42    False
43    False
44    False
45    False
46     True
47    False
48     True
49     True
Name: Avaliação do produto, dtype: bool

In [ ]:
filtro_categoria_produto

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13     True
14    False
15    False
16     True
17     True
18    False
19     True
20    False
21    False
22    False
23    False
24     True
25    False
26    False
27     True
28    False
29     True
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39     True
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: Categoria do produto, dtype: bool

In [ ]:
filtro_categoria_produto.shape

(50,)

In [ ]:
filtro_menor_2.shape

(50,)

In [ ]:
df_produtos[(df_produtos["Categoria do produto"] == "Informática") & (df_produtos["Preço do produto"] >= 350.0)]

,Nome do produto,Categoria do produto,Preço do produto,Quantidade vendida,Avaliação do produto
10,Produto_11,Informática,1351.14,2,3.0
13,Produto_14,Informática,1435.93,114,4.1
16,Produto_17,Informática,768.95,148,1.3
17,Produto_18,Informática,383.95,115,3.0
19,Produto_20,Informática,508.93,116,2.0
24,Produto_25,Informática,990.46,122,3.7
27,Produto_28,Informática,1751.42,66,2.1
29,Produto_30,Informática,442.31,52,1.7
39,Produto_40,Informática,694.05,20,2.6

In [ ]:
df_produtos.iloc[15]

Nome do produto          Produto_16
Categoria do produto    Componentes
Preço do produto            1218.39
Quantidade vendida                5
Avaliação do produto            3.1
Name: 15, dtype: object

In [ ]:
df_produtos.iloc[43:]

,Nome do produto,Categoria do produto,Preço do produto,Quantidade vendida,Avaliação do produto
43,Produto_44,Componentes,719.67,46,2.6
44,Produto_45,Acessórios,786.37,156,3.1
45,Produto_46,Eletrônicos,54.37,121,3.5
46,Produto_47,Acessórios,1811.84,44,1.5
47,Produto_48,Eletrônicos,811.68,74,2.3
48,Produto_49,Componentes,1886.37,143,1.1
49,Produto_50,Acessórios,1560.70,44,1.1

In [ ]:
df_produtos_indexed = df_produtos.set_index("Nome do produto")
#display(df_produtos_indexed)
df_produtos_indexed

,Categoria do produto,Preço do produto,Quantidade vendida,Avaliação do produto
Nome do produto,,,,
Produto_1,Componentes,857.64,138,2.9
Produto_2,Acessórios,1503.65,58,1.8
Produto_3,Acessórios,404.40,195,1.8
Produto_4,Componentes,1105.61,177,3.4
Produto_5,Acessórios,952.10,87,4.8
Produto_6,Acessórios,36.76,10,2.9
Produto_7,Periféricos,1040.82,79,2.7
Produto_8,Periféricos,800.41,60,4.6
Produto_9,Componentes,1316.04,143,3.8
Produto_10,Componentes,720.04,20,4.0
Produto_11,Informática,1351.14,2,3.0
Produto_12,Acessórios,374.64,42,2.0
Produto_13,Acessórios,1917.02,194,2.2
Produto_14,Informática,1435.93,114,4.1
Produto_15,Acessórios,1938.07,22,4.9
Produto_16,Componentes,1218.39,5,3.1
Produto_17,Informática,768.95,148,1.3
Produto_18,Informática,383.95,115,3.0
Produto_19,Acessórios,721.19,176,1.1
Produto_20,Informática,508.93,116,2.0
Produto_21,Acessórios,1066.93,171,3.0
Produto_22,Componentes,930.38,173,3.9
Produto_23,Componentes,1744.26,54,4.7
Produto_24,Componentes,954.57,183,4.5
Produto_25,Informática,990.46,122,3.7
Produto_26,Periféricos,982.93,127,2.4
Produto_27,Eletrônicos,512.88,62,2.7
Produto_28,Informática,1751.42,66,2.1
Produto_29,Componentes,952.24,189,4.3
Produto_30,Informática,442.31,52,1.7
Produto_31,Componentes,824.67,7,4.1
Produto_32,Eletrônicos,1185.93,155,4.4
Produto_33,Componentes,352.62,171,2.9
Produto_34,Componentes,358.93,113,1.7
Produto_35,Componentes,245.67,187,3.0
Produto_36,Eletrônicos,1550.08,159,2.4
Produto_37,Periféricos,1645.40,37,2.3
Produto_38,Periféricos,1081.01,173,4.0
Produto_39,Eletrônicos,212.39,112,3.9
Produto_40,Informática,694.05,20,2.6
Produto_41,Acessórios,1943.37,122,1.6
Produto_42,Componentes,1555.46,95,2.1
Produto_43,Periféricos,66.94,190,4.3
Produto_44,Componentes,719.67,46,2.6
Produto_45,Acessórios,786.37,156,3.1
Produto_46,Eletrônicos,54.37,121,3.5
Produto_47,Acessórios,1811.84,44,1.5
Produto_48,Eletrônicos,811.68,74,2.3
Produto_49,Componentes,1886.37,143,1.1
Produto_50,Acessórios,1560.70,44,1.1